### ISSUE TITLE
Add the setObjectMapper method to the ObjectMapperWrapper class

### ISSUE THREAD

**Issue by fdubuisson** [vladmihalcea/hypersistence-utils#304]
Current method to provide a custom object mapper through code (as described here: https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/) is not possible in Spring Boot, as the Hibernate configuration is not reachable (unless writing custom configuration, where we want to let the auto-configuration do the job).

Could there be a simple setter, for example on the `ObjectMapperWrapper` to directly provide the custom mapper?
 That way, we could write this in our Spring configuration class:
```
Configuration.INSTANCE.objectMapperWrapper.setObjectMapper(customMapper);
```

**Comment by vladmihalcea** [comment]
It's true that the Spring Boot `application.properties` is not used, but you can define the `hibernate.types.jackson.object.mapper` in a `hibernate-types.properties` file, and everything will work fine in Spring Boot too.

Or, even better. You can add support in the `Configuration` class to scan the `application.properties` too.

So, here's what you need to do:

1. Create a new issue "Add support for loading settings from an application.properties file"
2. Add support for this feature in the [`load` method](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/util/Configuration.java#L67). Most likely, you can provide the file name to the `propertiesInputStream` method call.
3. Send me a Pull Request so that I can validate and integrate it.

**Comment by fdubuisson** [comment]
It is not about where to define properties but about using a mapper instance already configured. For example, Spring already provides an instance with some settings and automatically discovers/registers serialization classes annotated with `@JsonComponent` at runtime.
So, I'm looking for a way to directly inject the instance that was build and configured by Spring.

**Comment by vladmihalcea** [comment]
@fdubuisson The `PropertyKey.JACKSON_OBJECT_MAPPER` setting could be set at runtime before you bootstrap the `EntityManagerFactory` to a `Supplier` that gives the object configured by Spring:

```
else if (objectMapperPropertyInstance instanceof Supplier) {
	Supplier<ObjectMapper> objectMapperSupplier = (Supplier<ObjectMapper>) objectMapperPropertyInstance;
	objectMapperWrapper = new ObjectMapperWrapper(objectMapperSupplier.get());
}
```

Now, the current implementation loads the default properties from `org.hibernate.cfg.Environment.getProperties()`, so you could pass that like this:

    System.getProperties().set(PropertyKey.JACKSON_OBJECT_MAPPER, myCustomObjectSupplier);

**Comment by vladmihalcea** [comment]
What can be done is adding a `ThreadLocal` in the Configuration class, which can allow passing the `ObjectMapperWrapper` That one could be used to cache the already computed one as, now, the `Configuration.getObjectMapperWrapper()` always extracts it, so if e have multiple `JsonType`, the `ObjectMapperWrapper` is instantiated multiple times.

**Comment by Tom-Ritense** [comment]
I really need this option to be implemented can I help? 
I could not find a way to do what you suggested above: _The PropertyKey.JACKSON_OBJECT_MAPPER setting could be set at runtime before you bootstrap the EntityManagerFactory to a Supplier that gives the object configured by Spring._

**Comment by vladmihalcea** [comment]
@Tom-Ritense At the moment, I don't have too much free time to work on OSS. If your company needs this and is willing to sponsor the development of this feature, then check out my [consulting offering](https://vladmihalcea.com/consulting/).

**Comment by Tom-Ritense** [comment]
For now I used the solution proposed in https://stackoverflow.com/questions/66656772/use-jackson-objectmapper-configured-by-spring-boot-in-hibernate works fine. I might create a PR in the future.

**Comment by vladmihalcea** [comment]
Looking forward to your PR then.

**Comment by RemboL** [comment]
Hi, I've just stumbled upon the same problem (want to use spring-provided objectMapper in hibernate-types), although I was trying to handle it from different approach.

I wanted to initialize JavaType with spring-provided objectMapper inside spring @Configuration and somehow register it in hibernate basic type registry (using [this](https://www.baeldung.com/hibernate-custom-types) guide and [this](https://stackoverflow.com/a/67879639) answer as reference) but so far I was unsuccessful (seems that this solution is not compatible with spring-boot-data-jpa).

Still thinking that this approach is most promising, I'll post an update if I succeed.

**Comment by SimonHarmonicMinor** [comment]
@RemboL We've implemented this solution in our project to set the `ObjectMapper` instance configured by Spring. Look at the code example below.

```java
@Component("HibernateObjectMapperSupplier")
public class HibernateObjectMapperSupplier implements ObjectMapperSupplier {
    private static final AtomicReference<ObjectMapper> objectMapper = new AtomicReference<>();

    @Autowired
    private void setObjectMapper(ObjectMapper mapper) {
        objectMapper.set(mapper);
    }

    @Override
    public ObjectMapper get() {
        return objectMapper.get();
    }

    @Component
    static class ObjectMapperDependencyFixer implements BeanFactoryPostProcessor {

        @Override
        public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) {
            final var beanDefinition = beanFactory.getBeanDefinition("entityManagerFactory");
            beanDefinition.setDependsOn(
                Stream.concat(
                    Stream.of(Objects.requireNonNullElse(beanDefinition.getDependsOn(), new String[]{})),
                    Stream.of("HibernateObjectMapperSupplier")
                ).toArray(String[]::new)
            );
        }
    }
}
```

And now you need to set the property in the `application.yml`:

```
spring:
  jpa:
    properties:
      hibernate:
        types:
          jackson:
            object:
              mapper: com.your.company.pckg.HibernateObjectMapperSupplier
```

That's a dirty hack but it's working. @vladmihalcea mind to add this example to the `README`?

**Comment by vladmihalcea** [comment]
Fixed.
