### ISSUE TITLE
Rename project to Hypersistence Utils

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-utils#534]
Since the project offers more than just Hibernate Types, it's time to rename it to Hypersistence Utils.

The base package and the Maven dependency will change as well.

Since this is a backward incompatible change, the change will happen in the 3.0 version of the project.

**Comment by piotrooo** [comment]
IMHO this is not an enchantment but a breaking change.

**Comment by vladmihalcea** [comment]
It is a backward incompatible change, just like the one that happened between Hibernate 2 and Hibernate 3.

For existing projects, they will have to:

- change the dependency 
- update the package names

It's the same as Java EE to Jakarta EE.

**Comment by vladmihalcea** [comment]
Fixed.
