### ISSUE TITLE
Cannot invoke "JsonSerializer.clone(Object)" because "this.jsonSerializer" is null

### ISSUE THREAD

**Issue by Hayo-Baan** [vladmihalcea/hypersistence-utils#538]
I am upgrading our applications and libraries to hypersistence utils 3.0.0 and am now facing the following issue:

`Cannot invoke "io.hypersistence.utils.hibernate.type.util.JsonSerializer.clone(Object)" because "this.jsonSerializer" is null`.

Some more testing actually reveals this is caused by changes implemented in 2.21.1 (2.20.0 and also 2.21.0 work fine), so this might be related to #530 and/or #533.

Something else I noted that may be related: I have set the `hibernate.types.jackson.object.mapper` in `hibernate.properties` to make use of my own object mapper. When running the application (or tests) in debug mode though, I can see the get method of the provider class it is _not_ called when using version 3.0.0. It _is_ called with 2.21.1 though, so this is not the cause of the issue, but still maybe related.
Note: I did check the source code of the `Configuration.java` file but while that did change between 2.20.0 and 2.21.0, there were no real changes in 3.0.0, so I don't understand why in 2.21.1 the object mapper provider get is called, but in 3.0.0 it is not…

**Comment by vladmihalcea** [comment]
Try to provide a replicating test case for the issue as all current integration tests run just fine.

**Comment by Hayo-Baan** [comment]
I'll try to create a simple test case. Our code, heavily uses custom query database and other libraries so this might be a bit hard without exposing all that proprietary code. If I can't come up with a clean example, could I perhaps send you one an example application, privately?

**Comment by vladmihalcea** [comment]
@Hayo-Baan Nevermind. I managed to replicate it and will provide a quick fix.

**Comment by Hayo-Baan** [comment]
Awesome, you're the greatest!

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vladmihalcea** [comment]
@Hayo-Baan Let me know if the issue is fixed on 3.0.1.

**Comment by Hayo-Baan** [comment]
@vladmihalcea Yes, everything is working fine in 3.0.1. Many thanks for the quick fix!)

(thought I replied this yesterday already, but I guess I forgot to post the comment 🙄)

**Comment by vladmihalcea** [comment]
Great 👍 Stay tuned for some really cool features that will come in the next releases.
