### ISSUE TITLE
JsonType wrong param binding for mutation query

### ISSUE THREAD

**Issue by belovaf** [vladmihalcea/hypersistence-utils#541]
hibernate version: 6.1.6.Final
hibernate-types-60 version: 2.21.1

Steps to reproduce:
1) Annotate an entity field with `@Type(JsonType.class)`.
2) Execute a mutation query to update the field, for example:
```
session
  .createMutationQuery("update MyEntity set jsonField = :jsonField")
  .setParameter("jsonField", new MyJsonType())
  .executeUpdate()
```

After some research I found a cause for this problem.

Class `AbstractJdbcParameter` contains the following fragment:
```
// If the parameter type is not known from the context i.e. null or Object, infer it from the bind value
if ( jdbcMapping == null || jdbcMapping.getMappedJavaType().getJavaTypeClass() == Object.class ) {
  jdbcMapping = guessBindType( executionContext, bindValue, jdbcMapping );
}
```

All your custom json types always return `Object.class` because they inherited from `AbstractClassJavaType`.
Temporarily workaround example:
```
public class CustomJsonJavaTypeDescriptor extends JsonJavaTypeDescriptor {
    private Class customType = Object.class;

    @Override
    public void setParameterValues(Properties parameters) {
        super.setParameterValues(parameters);
        customType = ((ParameterType) parameters.get(PARAMETER_TYPE)).getReturnedClass();
    }

    @Override
    public Class<Object> getJavaType() {
        return customType;
    }
}

public class CustomJsonType extends MutableDynamicParameterizedType<Object, JsonJdbcTypeDescriptor, CustomJsonJavaTypeDescriptor> {
    public CustomJsonType() {
        super(Object.class, new JsonJdbcTypeDescriptor(), new CustomJsonJavaTypeDescriptor());
    }
}
```

I propose following solution:
1) Don't extend from AbstractClassJavaType because it has `private final Class<T> type` and reimplement it logic.
2) Set type dynamically in `setParameterValues` method.

**Comment by vladmihalcea** [comment]
The `JsonType` is not auto-registered, so you have to provide the type explicitly when you bind it.

Son, instead of:

````
session
  .createMutationQuery("update MyEntity set jsonField = :jsonField")
  .setParameter("jsonField", new MyJsonType())
  .executeUpdate()
````

You need to use:

````
session
  .createMutationQuery("update MyEntity set jsonField = :jsonField")
  .setParameter("jsonField", new MyJsonType(), new JsonType(MyJsonType.class))
  .executeUpdate()
````

That's it!

Here are two test cases that show you this in practice:

- [`GenericPostgreSQLJsonTypeTest`](https://github.com/vladmihalcea/hypersistence-utils/blob/e3d0f82c928675f4705ed9d3ef815d9aa987e547/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/generic/GenericPostgreSQLJsonTypeTest.java#L107)
- [`GenericMySQLJsonTypeTest`](https://github.com/vladmihalcea/hypersistence-utils/blob/e3d0f82c928675f4705ed9d3ef815d9aa987e547/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/generic/GenericMySQLJsonTypeTest.java#L129)

**Comment by belovaf** [comment]
Thank you for so fast response!

1) Hibernate can detect a binding from the field, so you can bind a value without the third param. Actually it worked in hibernate-types-55.
2) Can you try to replace Location with a custom not serializable type (our case)? I see serialization exception in this case. This happens because hibernate picks wrong mutability plan from wrong JavaType.
3) If I replace `JsonType` with `CustomJsonType` from my example all works fine even without providing the `JsonType` explicitly.

**Comment by vladmihalcea** [comment]
> Hibernate can detect a binding from the field, so you can bind a value without the third param. Actually it worked in hibernate-types-55.

Hibernate 6 changed the Type system significantly, and the auto-registration no longer works as before.

> Can you try to replace Location with a custom not serializable type (our case)? I see serialization exception in this case. This happens because hibernate picks wrong mutability plan from wrong JavaType.

Yes, you can remove the `Serializable` from that `Location` class and it will still work just fine. The test cases are available in the project so you can validate this yoo.

> If I replace JsonType with CustomJsonType from my example all works fine even without providing the JsonType explicitly.

It also works just fine with the `JsonType` and the explicit Type, as I have shown you. In fact, providing the `Type` explicitly for queries has been the [default way of working](https://vladmihalcea.com/hibernate-no-dialect-mapping-for-jdbc-type/) for this library.

However, if you think you are better off using your `CustomJsonType`, then you shall use that one instead.

**Comment by vladmihalcea** [comment]
@belovaf Actually, as I explained in [this article](https://vladmihalcea.com/bind-custom-hibernate-parameter-type-jpa-query/), there's another alternative via the `TypedParameterValue`.

This is a Hibernate constructor that was designed exactly for this use case:

```
session
  .createMutationQuery("update MyEntity set jsonField = :jsonField")
  .setParameter("jsonField", new TypedParameterValue<>(new JsonType(MyJsonType.class), new MyJsonType()))
  .executeUpdate()
```

**Comment by belovaf** [comment]
@vladmihalcea, I debug mentioned by you test cases. I didn't notice that they use nativeQuery.
My issue is relevant only to hibernate mutation query (hql).
If you want, I can make a pull request which demonstrates the problem.

**Comment by belovaf** [comment]
You are absolutely right about natives queries. One indeed need to provide a typed parameter for them. But when a hql query is used hibernate detects parameter type automatically from the corresponding field.

**Comment by vladmihalcea** [comment]
@belovaf For JPQL is even simpler. All you need is just register the Type, like this:


```
properties.put("hibernate.type_contributors",
    (TypeContributorList) () -> Collections.singletonList(
        (typeContributions, serviceRegistry) ->
            typeContributions.contributeType(locationJsonType)
    )
);
```

Once you do that, your query is as simple as:

```
entityManager.createQuery(
    "update Event " +
    "set location = :location " +
    "where id = :id")
.setParameter("id", _event.getId())
.setParameter("location", location)
.executeUpdate();
```

You can see the example in [`GenericMySQLRegisterJsonTypeTest`](https://github.com/vladmihalcea/hypersistence-utils/blob/ecf89dc87db35702e8c985b49ec4c8b92f578d8e/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/generic/GenericMySQLRegisterJsonTypeTest.java).

The fact that this is not resolved automatically is a Hibernate issue for which you should open a Jira issue.

**Comment by vladmihalcea** [comment]
I created [HHH-15953](https://hibernate.atlassian.net/browse/HHH-15953) for this.

**Comment by belovaf** [comment]
@vladmihalcea, thank you very much!
Your involvement and reply speed are outstanding!

**Comment by vladmihalcea** [comment]
At Hypersistence, High-Performance is the normal velocity.

**Comment by joshiste** [comment]
Thanks for this issue. I ran exactly into the same problem using the `JsonBinaryType` with Hibernate 6. Thanks for the good work!

**Comment by vladmihalcea** [comment]
@joshiste You're welcome. Stay tuned for more
