### ISSUE TITLE
Could not determine recommended JdbcType for `com.fasterxml.jackson.databind.JsonNode`

### ISSUE THREAD

**Issue by tcheeric** [vladmihalcea/hypersistence-utils#542]
Hi Vlad,

I am trying to replicate [this example](https://vladmihalcea.com/how-to-store-schema-less-eav-entity-attribute-value-data-using-json-and-hibernate/) with the latest version, v.3.0.1, but It doesn't seem to work. Here below is the error message I receive. The error occurs while creating the entity manager factory (`EntityManagerFactory`) in my client class.

> Exception in thread "main" org.hibernate.type.descriptor.java.spi.JdbcTypeRecommendationException: Could not determine recommended JdbcType for `com.fasterxml.jackson.databind.JsonNode`

Here's my entity class:

```java
import com.fasterxml.jackson.databind.JsonNode;
import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.TypeDef;

/**
 *
 * @author squirrel
 */
@Entity(name = "Event")
@Table(name = "p_event")
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@TypeDef(
        typeClass = JsonBinaryType.class,
        defaultForType = JsonNode.class
)
@ToString
public class Event implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Long id;

    @Column(columnDefinition = "jsonb")
    private JsonNode data;
}
```

**Comment by vladmihalcea** [comment]
All the examples in the docs are available in the src/test folders.

In your case, [this is the test case you were looking for](https://github.com/vladmihalcea/hypersistence-utils/blob/e8ca3253bcfd10864d9a14174c72666c50aeccaa/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/PostgreSQLJsonNodeTypeTest.java#L224).

You'll find more examples there, and they all work like a charm.

Compare the existing examples with yours and see where they differ.

**Comment by tcheeric** [comment]
Thanks for the prompt reply. I am looking into it now.

**Comment by tcheeric** [comment]
I confirm, works like a charm! :)
Many Thanks!

**Comment by vladmihalcea** [comment]
You're welcome.
