### ISSUE TITLE
DTO Projection with PostgreSQLEnumType fails using Hibernate 6

### ISSUE THREAD

**Issue by thomas14129** [vladmihalcea/hypersistence-utils#547]
Using Hibernate 6.1.6.Final, doing a DTO projection with an enum fails.
```
        CriteriaBuilder builder = entityManager.getCriteriaBuilder();

        CriteriaQuery<PostDto> criteria = builder
            .createQuery(PostDto.class);

        Root<Post> postComment = criteria.from(Post.class);

        criteria.select(builder.construct(PostDto.class,
            postComment.get("status")));

        TypedQuery<PostDto> criteriaQuery = entityManager
            .createQuery(criteria);

        // this fails with "java.lang.IllegalStateException: Could not
        // determine appropriate instantiation strategy - no matching
        // constructor found and one or more arguments did not define alias
        // for bean-injection"
        List<PostDto> p = criteriaQuery.getResultList();
```

I created some test cases showing that it works with Hibernate 5, but not with Hibernate 6: https://github.com/thomas14129/hypersistence-utils/tree/enum-projection-mapping-fails

This is happening with `CriteriaBuilder` and also `entityManager.createQuery`. I'm actually not 100% sure if that's an issue with this library or with Hibernate itself.

Any idea?

**Comment by vladmihalcea** [comment]
It's because of #532

It works only with Hibernate `6.0`. Something has changed in 6.1 that breaks the `PostgreSQLEnumType`. You could investigate it if you want and provide a Pull Request with a fix proposal.
