### ISSUE TITLE
Cannot invoke "JsonSerializer.clone(Object)" because "this.jsonSerializer" is null in 2.21.1

### ISSUE THREAD

**Issue by idegroot** [vladmihalcea/hypersistence-utils#549]
We are facing the same issue as https://github.com/vladmihalcea/hypersistence-utils/issues/538 when updating from 2.20.0 to 2.21.1. 

The error in this version is:

`Cannot invoke "com.vladmihalcea.hibernate.type.util.JsonSerializer.clone(Object)" because "this.jsonSerializer" is null`

We are not ready yet to update to 3.0.1. Would it be possible to apply the fix also to 2.21.x?

**Comment by vladmihalcea** [comment]
The upgrade to 3.x takes 2 minutes and provides you the fix.

The 2.x branch is no longer maintained.
