### ISSUE TITLE
Spring failing to run because of unknow property

### ISSUE THREAD

**Issue by arthurgregorio** [vladmihalcea/hypersistence-utils#553]
After adding the hypersistence-utils to my project spring started to failing when starting. The error says:

`Caused by: org.springframework.data.mapping.PropertyReferenceException: No property 'update' found for type 'Authority'
	at app//org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:90)
`

But there is no property with that name in my entity (can be seen [here](https://github.com/web-budget/back-end/blob/main/src/main/kotlin/br/com/webbudget/domain/entities/administration/Authority.kt)) and seens to be spring trying to read the `update` method from `HibernateRepository` as an operation with a property with the same name in this entity.

Removing the `HibernateRepository` all tests run successfully.

I'm using:
- spring boot 3.0.1
- Kotlin 1.8
- Hibernate 6.1

Any clue on what could be the issue?

**Comment by vladmihalcea** [comment]
Make sure you added `io.hypersistence.utils.spring.repository` to the `@EnableJpaRepositories`.

````
@Configuration
@EnableJpaRepositories(
    basePackages = {
        "io.hypersistence.utils.spring.repository",
        "your.repository.package",
        ...
    }
)
public class JpaConfiguration {
    ...
}
````

Check out the existing integration tests for a reference.

**Comment by arthurgregorio** [comment]
Yes, the config [is there](https://github.com/web-budget/back-end/blob/main/src/main/kotlin/br/com/webbudget/infrastructure/config/spring/PersistenceConfig.kt) and before asking here I saw the same problema reported [here](https://github.com/vladmihalcea/hypersistence-utils/issues/461)

But even using like this, the error appears. If I just remove the hibernate repository from my default repository [here](https://github.com/web-budget/back-end/blob/main/src/main/kotlin/br/com/webbudget/infrastructure/repository/DefaultRepository.kt), everything works fine and the application starts (tests run).

The desired outcome here is: tests run but fail with the save method throwing a `UnsupportedOperationException`, this means I need now to replace all save methods by the update/persist ones

**Comment by vladmihalcea** [comment]
It's better to use the `BaseJpaRepository` instead of the `HibernateRepository`. Check out [this article](https://vladmihalcea.com/basejparepository-hypersistence-utils/) for more details.

**Comment by arthurgregorio** [comment]
At the end, found out what is the problem, kind weird must say but understandable ahaha

The fact that I use a base repository to "hide" the implementations is the reason. Moving the extends for the `HibernateRepository` (and it worked the same for the `BaseJpaRepository`) to my entity repository rather than my custom default repo solved the issue.

The reason I could found for that problem is something around spring not being able to pick the correct implementation for the repository since it will search a class with the same name but with `Impl` as a sufix. Thats why he was complaining on method names not being related to a declared property inside the class.

The bad thing (not really a problem, but IMO is bad) here is: now, if I want to use the `HibernateRepository` or the `BaseJpaRepository` I need to add it to every entity repository I have.

Code with the fix for the error will be on my repo soon and them I can link the files here for a better understanding.

**Comment by vladmihalcea** [comment]
> The bad thing (not really a problem, but IMO is bad) here is: now, if I want to use the HibernateRepository or the BaseJpaRepository I need to add it to every entity repository I have.

There's nothing bad, actually. Again, you shouldn't be using `HibernateRepository`, as that's just a work-around. You should be using `BaseJpaRepository` instead.

Now, using `BaseJpaRepository` is the same as using `JpaRepository`:

- where you'd previously extend `JpaRepository`, you now extend `BaseJpaRepository`
- where you'd previously set the `@EnableJpaRepositories` to locate the base packages, you now have to add the `repositoryBaseClass`

That's it.

**Comment by arthurgregorio** [comment]
Yeah, I mean bad because I have to do the implementation it in every repo I have and not in a single place (my custom repo) like I was doing before. But not a big issue.

**Comment by vladmihalcea** [comment]
You don't have to implement anything. All you need to do is replace `JpaRepository` with `BaseJpaRepository` and add an `repositoryBaseClass` attribute to an existing `@EnableJpaRepositories`.

**Comment by vladmihalcea** [comment]
> The fact that I use a base repository to "hide" the implementations is the reason. Moving the extends for the HibernateRepository (and it worked the same for the BaseJpaRepository) to my entity repository rather than my custom default repo solved the issue.

The issue is closed, then.
