### ISSUE TITLE
JsonNodeBinaryType cannot bind a JsonNode parameter value

### ISSUE THREAD

**Issue by vkolodrevskiy** [vladmihalcea/hypersistence-utils#554]
Hello Vlad,

Thank you for this great project. I'm migrating from 55 to 60.
Using Postgres, hibernate 6.1.6 and hypersistence-utils-hibernate-60:3.1.1.

There's table with column `config` of type `jsonb`. Have corresponding POJO like:
```
@Entity
@Table(name = "t_job")
public class Job {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Type(JsonBinaryType.class)
  @Column(name = "config", columnDefinition = "jsonb")
  private JsonNode config;
...
}
```
My repository looks like:
```
@Repository
@Transactional
public interface JobRepository extends JpaRepository<Job, Long> {
  @Query("SELECT job FROM Job job WHERE job.config = :config")
  ScheduledJob findJob(@Param("config") JsonNode config);
}
```
When calling `findJob` I get exception:
```
jakarta.persistence.PersistenceException: Converting `org.hibernate.type.descriptor.java.spi.JdbcTypeRecommendationException` to JPA `PersistenceException` : Could not determine recommended JdbcType for `com.fasterxml.jackson.databind.JsonNode`
```
If changing to `@Type(JsonNodeBinaryType.class)`
Got
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.fasterxml.jackson.databind.JsonNode (java.lang.String is in module java.base of loader 'bootstrap'; com.fasterxml.jackson.databind.JsonNode is in unnamed module of loader 'app')
```

Please advise why it's not working?

**Comment by vladmihalcea** [comment]
I have no idea why it may not be working, so here's what you will have to umdo:

- create a replicating test case in the project that proves the issue
- investigate how to fix the issue 
- provide a Pull Request with the fix

I'll review it after you are done with it.

**Comment by vkolodrevskiy** [comment]
But in general it should work with `@Type(JsonBinaryType.class)` or with `@Type(JsonNodeBinaryType.class)`? Right?

**Comment by vladmihalcea** [comment]
The latter option is the right one.

Use [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/e8ca3253bcfd10864d9a14174c72666c50aeccaa/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/PostgreSQLJsonNodeBinaryTypeTest.java) as a reference to replicate the issue.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vkolodrevskiy** [comment]
@vladmihalcea ,

You're quick :) If possible, can you do a small release with this fix maybe tomorrow please? That would really help.

Thank you

**Comment by vladmihalcea** [comment]
You're welcome. Unfortunately, I'll be busy the rest of the month and the next release will come in February or March.

You can build the project and use the SNAPSHOT artifact in the meantime.
