### ISSUE TITLE
java.lang.IllegalArgumentException: The given string value: {" mapping": {}} cannot be transformed to Json object

### ISSUE THREAD

**Issue by rohanm28** [vladmihalcea/hypersistence-utils#566]
Hello, 
I am using ` hypersistence-utils-hibernate-52` to store json document in mysql 8 table with spring boot.
The data is getting stored but when i trying to read it from db it is throwing 
ERROR 
`java.lang.IllegalArgumentException: The given string value: {" mapping": {}} cannot be transformed to Json object`

Here BaseDocumentEntity has annotation:

```
@TypeDefs({
    @TypeDef(name = "json", typeClass = JsonStringType.class)
})

public class UserDataDocument extends BaseDocumentEntity {

  @Column(name = "id", length = 64)
  private String id;
  @Type(type = "json")
  @Column(columnDefinition = "json")
  private UserData userData;

  @Data
  @Builder
  public static class UserData implements Serializable {

    private Map<String, BankDetails> mapping;
  }

  @Data
  @Builder
  public static class BankDetails implements Serializable {

    private String bankCode;
    private String bankName;
}

}
```

**Comment by vladmihalcea** [comment]
Try to debug it and see why it doesn't work. The source code is available in your IDE so you can debug and see what didn't work for you.

**Comment by rohanm28** [comment]
I tried debugging it. Initially the  Map<String, BankDetails> mapping was the json column but i wrapped it with UserData class. saving the data is working but idk why while reading it is breaking, i think it is not able to map the HashMap.

**Comment by rohanm28** [comment]
<img width="1103" alt="Screenshot 2023-01-30 at 9 52 11 PM" src="https://user-images.githubusercontent.com/114666715/215533743-4b17c06b-9e43-49d6-ac61-91c1268247d1.png">

**Comment by vladmihalcea** [comment]
Maybe it's because of that `@Data` and `@Builder` annotations. Try with standard Java Beans and see if it works.

**Comment by rohanm28** [comment]
Identified the issue!!!!
So basically if we are storing only map inside an object it is never able to map the object. But along with map the map if i am storing any other field it is working.

**Not working code:**

@Data
  @Builder
  public static class UserData implements Serializable {

    private Map<String, BankDetails> mapping;
  }

**Working Code:**

@Data
  @Builder
  public static class UserData implements Serializable {
    private String userId;
    private Map<String, BankDetails> mapping;
  }

**Comment by vladmihalcea** [comment]
I'm glad you found the solution,
