### ISSUE TITLE
Change signature of toString and areEqual methods in AbstractArrayTypeDescriptor to match those of its superclass

### ISSUE THREAD

**Issue by mjagus** [vladmihalcea/hypersistence-utils#569]
I'm trying to implement my own custom array type descriptor for one of my own classes and need to override toString method from `AbstractArrayTypeDescriptor` because default implementation simply calls `toString()` on my objects which is something I do not want. Unfortunately I'm getting following compiler error when doing so:

```
name clash: class StringTemplateArrayTypeDescriptor has two methods with the same erasure, yet neither overrides the other
  first method:  toString(StringTemplate[]) in org.hibernate.type.descriptor.java.JavaTypeDescriptor
  second method: toString(java.lang.Object) in io.hypersistence.utils.hibernate.type.array.internal.AbstractArrayTypeDescriptor
```

Here's minimalistic code sample which replicates the issue:
```java
import java.util.Arrays;
import java.util.stream.Collectors;

import io.hypersistence.utils.hibernate.type.array.internal.AbstractArrayTypeDescriptor;

final class StringTemplateArrayTypeDescriptor extends AbstractArrayTypeDescriptor<StringTemplate[]> {

    StringTemplateArrayTypeDescriptor() {
        super(StringTemplate[].class);
    }

    @Override
    public String toString(StringTemplate[] value) {
        return Arrays.stream(value)
                .map(StringTemplate::rawValue)
                .collect(Collectors.joining(",", "[", "]"));
    }

    @Override
    protected String getSqlArrayType() {
        return "varchar";
    }

}

record StringTemplate(String rawValue) {}
```

Changing the signature of my `toString` method to `public String toString(Object value)` doesn't help:
```
name clash: toString(java.lang.Object) in StringTemplateArrayTypeDescriptor and toString(StringTemplate[]) in org.hibernate.type.descriptor.java.JavaTypeDescriptor have the same erasure, yet neither overrides the other
```

I'm on JDK 19 and I'm using hypersistence-utils-hibernate-55, but from quick look in the repo, both hypersistence-utils-hibernate-52 and hypersistence-utils-hibernate-5 seem to also have this problem.

**Comment by vladmihalcea** [comment]
The base class method is:

    @Override
    public String toString(Object value) {
        return Arrays.deepToString(ArrayUtil.wrapArray(value));
    }

Therefore, you need to use the same method signature, just like this class overrides it from `AbstractTypeDescriptor`.

If using the same signature didn't work, the project would not compile or run.

**Comment by mjagus** [comment]
@vladmihalcea I already posted in the OP that changing signature to `public String toString(Object value)` doesn't work. Compiler error remains.

**Comment by vladmihalcea** [comment]
Maybe it's a Java 19 issue. The project compiles just fine on both Java 11 and 8 and that `toString` method is overriden in multiple classes.

**Comment by vladmihalcea** [comment]
@mjagus Try forking the project and see if it works this way.

In the `AbstractArrayTypeDescriptor` class, instead of:

    @Override
    public boolean areEqual(Object one, Object another) {
        if (one == another) {
            return true;
        }
        if (one == null || another == null) {
            return false;
        }
        return ArrayUtil.isEquals(one, another);
    }

    @Override
    public String toString(Object value) {
        return Arrays.deepToString(ArrayUtil.wrapArray(value));
    }

Do this:

    @Override
    public boolean areEqual(T one, T another) {
        if (one == another) {
            return true;
        }
        if (one == null || another == null) {
            return false;
        }
        return ArrayUtil.isEquals(one, another);
    }

    @Override
    public String toString(T value) {
        return Arrays.deepToString(ArrayUtil.wrapArray(value));
    }

Then, build the Hypersistence Utils project and see if it works. If it does, send me a Pull Request and I'll reopen the issue.

**Comment by mjagus** [comment]
This indeed fixes my issue. I created pull request https://github.com/vladmihalcea/hypersistence-utils/pull/577.

**Comment by vladmihalcea** [comment]
Thanks for confirming. I'll integrate it for the next release.

**Comment by vladmihalcea** [comment]
Fixed.
