### ISSUE TITLE
Maven Central Indexing

### ISSUE THREAD

**Issue by bcallender** [vladmihalcea/hypersistence-utils#575]
Hi Vlad, big fan of your work. 

I'm a current user of the hibernate-types library, and was trying to migrate to hyperpersistence-utils, but ran into a problem. I have to pull from an internal corporate repo for security reasons and for some reason the hyperpersistence-utils is not indexed there, only hibernate-types. I'm trying to figure out why, as I'm pretty sure we scrape all of the artifacts from maven central. I noticed that your previous library hibernate types is available on mvnrepository (https://mvnrepository.com/artifact/com.vladmihalcea/hibernate-types-55) in search, but hyperpersistence-utils does not appear at all on the site, even though I see it in the index [here](https://repo1.maven.org/maven2/io/hypersistence/hypersistence-utils-hibernate-60/). Is there a particular reason hyperpersistence-utils isn't showing up properly?

**Comment by bcallender** [comment]
The artifacts have magically appeared -- I swear I checked yesterday and they were not there and my project would not build if I changed the dependency, but now it suddenly works.

**Comment by vladmihalcea** [comment]
The [MvnRepository website](https://mvnrepository.com/artifact/com.vladmihalcea/hibernate-types-55) is a 3rd party app. It's not affiliated to Maven Central.

Better use [Sonatype](https://central.sonatype.com/namespace/io.hypersistence) instead.
