### ISSUE TITLE
Allow deserialization of polymorphic types with Jackson's EXTERNAL_PROPERTY

### ISSUE THREAD

**Issue by heitorneves91** [vladmihalcea/hypersistence-utils#580]
I have an entity that maps to an abstract class using jsonb type from Hypersistence Utils.
I don't want to add a type information to the serialized value because type information can be discovered looking at another column/property on the entity. Jackson allows this using JsonTypeInfo.As.EXTERNAL_PROPERTY but I cannot make it work with Hibernate.

```java
@TypeDefs(TypeDef(name = "jsonb", typeClass = JsonBinaryType::class))
public class MyEntity() {
  @Column(name = "name")
  private String name;

  @JsonTypeInfo(
      use = JsonTypeInfo.Id.NAME,
      include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
      property = "name",
  )
  @JsonIgnoreProperties(ignoreUnknown = true)
  @JsonSubTypes({
        @JsonSubTypes.Type(value = Concrete::class, name = "CONCRETE"),
  })
  @Column(name = "some_data", columnDefinition = "jsonb")
  @Type(type = "jsonb")
  private SomeAbstract someData;
}
```

Found @vladmihalcea 's article on mapping polymorphic but it does not mention EXTERNAL_PROPERTY. Can I make it work anyway or, if not, is it possible for it to be added to future releases?

Thank you very much

**Comment by vladmihalcea** [comment]
> I don't want to add a type information to the serialized value because type information can be discovered looking at another column/property on the entity.

You can also use a `JsonNode` as the entity attribute and then use that along with the extra `property` to build the actual subclass instance you want in a `PostLoad` callback.

Check out [this article](https://vladmihalcea.com/encrypt-decrypt-json-jpa/) for more details about transforming the JSON data before you save and after you load from the DB.

**Comment by heitorneves91** [comment]
I didnt know about those annotation. I can add another field just for mapping as JsonNode, say _data and then map to a @Transient data by choosing the proper implementation. That really seems to do the trick.

I implemented a similar but inefficient approach by only using getters and setters of the new property but deserialization would occur on every access which can be awful.

Thank you so much for the fast reply

**Comment by vladmihalcea** [comment]
You're welcome. I'm going to close the issue since you found a solution.
