### ISSUE TITLE
PostgreSQLPeriodType refers to Duration in Javadoc

### ISSUE THREAD

**Issue by OLibutzki** [vladmihalcea/hypersistence-utils#586]
The Javadoc of `PostgreSQLPeriodType` says:
> Maps a Java {@link Duration} object to a PostgreSQL Interval column type.

I guess it should have been
> Maps a Java {@link Period} object to a PostgreSQL Interval column type.

**Comment by vladmihalcea** [comment]
I guess that too

**Comment by vladmihalcea** [comment]
Fixed.
