### ISSUE TITLE
Could not determine recommended JdbcType.

### ISSUE THREAD

**Issue by settlersxp** [vladmihalcea/hypersistence-utils#588]
Hello, 
In the first place thank you for all you work you've done with this dependency it is very useful.

I updated yesterday my spring-boot project from 2.6 to 3.0.4, I did all the changes required to start the project again, and everything works fine except saving a JsonNode into db.

I've added the following dependencies: 

```
implementation group: 'io.hypersistence', name: 'hypersistence-utils-hibernate-60', version: '3.2.0'
implementation group: 'com.fasterxml.jackson.module', name: 'jackson-module-jakarta-xmlbind-annotations', version: '2.14.2'
```
The last one I added after I read your doc and other sources.

I've removed  from class level:

`@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)`

And replace 

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private JsonNode someName;`

With:

    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    private JsonNode headerBody;`

And when I try to insert in the db I'm getting this error:

    Could not determine recommended JdbcType for `com.fasterxml.jackson.databind.JsonNode`

Is there anything that I'm missing here that I'm not aware of or that could be a potential issue?

**Comment by vladmihalcea** [comment]
You can use [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/generic/GenericPostgreSQLJsonNodeTest.java#L19) as a reference and see how it differs from your mapping.

That test case runs just fine, so you can do a comparison in debug mode between my test and your application and see where they diverged.

**Comment by settlersxp** [comment]
Thank you for that, I will have a look. 

Meanwhile, I found something on the hibernate doc, and it seems to work If I replace @Type(JsonType.class) with @JdbcTypeCode(SqlTypes.JSON). More info [HERE](https://www.jpa-buddy.com/blog/hibernate6-whats-new-and-why-its-important/)

But I'm getting a warning (Attribute with unsupported type should either be @Transient or have custom type or converter declaration ). So not sure what to do now.

I will try to investigate more your test. It is a bit different than my scenario, where I receive directly a JsonNode through an HTTP call and try to insert it straight away.
Thx anyway.

**Comment by vladmihalcea** [comment]
My test doesn't use `JdbcTypeCode(SqlTypes.JSON)` and works just fine.

**Comment by settlersxp** [comment]
I know yours doesn't use `JdbcTypeCode(SqlTypes.JSON`, but I wanted just to point out the workaround.
So based on your replies what I understand is, the problems come from somewhere else, and the config which I've made is correct. 
I had a look at your test cases and the only difference is the way you insert things in db. But that it should not trigger such an error.

I will keep investigating but thank you for your time.

**Comment by settlersxp** [comment]
I'm not sure what annotation you refer to. If you don't mind could you please be more specific? Thank you.

**Comment by vladmihalcea** [comment]
You used a single extra annotation: `JdbcTypeCode(SqlTypes.JSON`

**Comment by settlersxp** [comment]
Oh yes, but that is not extra...is either that annotation or yours. And for some reason, that one is working and yours is not, and as far as I understand that annotation is built in now in hibernate 6. x or bigger.
So to be more specific my current setup in my entities classes looks like this.

```
    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    @NotNull
    private JsonNode actorValues;
```

And with the workaround, by using hibernate functionality looks like this:

`    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode headerBody;`

**Comment by vladmihalcea** [comment]
Great. Then, this issue can be closed now.
