### ISSUE TITLE
Expose Range utility methods

### ISSUE THREAD

**Issue by Hc747** [vladmihalcea/hypersistence-utils#594]
It would be really handy to be able to access the following methods within `io.hypersistence.utils.hibernate.type.range.Range`.

`Range#hasEqualBounds`
`Range#isBoundedOpen`
`Range#isBounded`

Are there any reasons why these _should_ be encapsulated?

**Comment by Hc747** [comment]
> @Hc747 If you think they are useful, then you can make the change and send a Pull Request with that.

Opened in #595

**Comment by vladmihalcea** [comment]
Fixed.
