### ISSUE TITLE
Error: cannot execute INSERT in a read-only transaction

### ISSUE THREAD

**Issue by xomak** [vladmihalcea/hypersistence-utils#598]
After replacement JpaRepository to BaseJpaRepository
@Service reports: Error: cannot execute INSERT in a read-only transaction during inserts.
methods with inserts are not using @Transactional.
Adding @Transaction(readonly = false) on @Service class level fixes it.
What's the reason and how to use BaseJpaRepository correctly without @Transactional?(if it is possible) 

Thank you in advance

**Comment by vladmihalcea** [comment]
The transaction boundaries should be set by the Service Layer, not by the Data Access Layer.

If you don't set the `@Transactional` annotation on your Service method and you call 3 methods on the Repository, each method will execute in its own transaction and will cause 3 connection acquisitions from the pool.

Anyway, #584 fixes this issue so this problem should be fixed even if you use transactions on the `Repository`, which you should not.

**Comment by xomak** [comment]
We din't have any @Transcational annotations before,(not on service, and of course not in repository level). That's the reason of the question, we just switched JpaRepository to BaseJpaRepository , and received the error.  
for e.g. 
---before
public interface SaleRepository extends JpaRepository<Sale, UUID>
{.}
@Service
someLongRunningMethod(){
...
saleRepository.save(entity);
...}

----after
@Repository
public interface SaleRepository extends BaseJpaRepository<Sale, UUID>
{}

@Service
someLongRunningMethod(){
...
//and this is now not working - cannot execute INSERT in a read-only transaction
saleRepository.persist(entity);
...
}
----> 
@Transactional(readOnly = false)
@Service
someLongRunningMethod(){
...
//now it works
saleRepository.persist(entity);
...
}
but now we have to use @Transactional and refactor the code in order not to have too long running database transaction

**Comment by vladmihalcea** [comment]
You can try the 3.3.0 version as it should work without you doing any change.

**Comment by xomak** [comment]
> You can try the 3.3.0 version as it should work without you doing any change.

thank you!

**Comment by vladmihalcea** [comment]
You're welcome
