### ISSUE TITLE
Adapt the Hibernate 6.2 module to the new Type and BasicPluralJavaType changes

### ISSUE THREAD

**Issue by cigaly** [vladmihalcea/hypersistence-utils#602]
Changes between last candidate (CR4) and final versionsare causing some of types to be unusable when running together with Hibernate ORM 6.2.0.Final. To make it work, it will be enough to implement io.hypersistence.utils.hibernate.type.ImmutableType.compare(Object, Object, SessionFactoryImplementor) 
and
io/hypersistence.utils.hibernate.type.array.internal.AbstractArrayTypeDescriptor.resolveType(TypeConfiguration, Dialect, BasicType, ColumnTypeInformation, JdbcTypeIndicators)
Most likely, existing methods with same name, but slightly different parameters can be used.

**Comment by vladmihalcea** [comment]
Send me a Pull Request with the changes in place, and I'll integrate it after review.

**Comment by vladmihalcea** [comment]
Fixed.
