### ISSUE TITLE
Hibernate 6 and CriteriaBuilder function for Postgres ANY() fails

### ISSUE THREAD

**Issue by dirkluijk** [vladmihalcea/hypersistence-utils#605]
Hi,

Not sure if this is a bug. I have am entity with this field (example is in Kotlin):
```kotlin
@Embeddable
data class Criteria(

    @Type(ListArrayType::class)
    @Column(columnDefinition = "text[]")
    val brands: List<String> = emptyList()

    /* .. */
}
```

To check if the list contains that value, I was using the following criteria builder solution:

```kotlin
cb.equal(cb.literal(value), cb.function("any", String::class.java, path))
```

After I upgraded to Spring Boot 3 and Hibernate 6 and made the adjustments as documented (snippet below is what I now have), I am getting this error:
```
 java.lang.NullPointerException: Cannot invoke "org.hibernate.type.descriptor.jdbc.JdbcType.getDefaultSqlTypeCode()" because "jdbcType" is null
	at org.hibernate.query.sqm.produce.function.ArgumentTypesValidator.validate(ArgumentTypesValidator.java:92)
	at org.hibernate.query.sqm.function.AbstractSqmFunctionDescriptor.generateSqmExpression(AbstractSqmFunctionDescriptor.java:104)
	at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.function(SqmCriteriaNodeBuilder.java:1500)
	at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.function(SqmCriteriaNodeBuilder.java:153)
	at my.app.postgres.Criteria_utilsKt.arrayContains(criteria-utils.kt:13)
```

I fixed this by rewriting it to:

```kotlin
cb.isNotNull(cb.function("array_position", Integer::class.java, path, cb.literal(value)))
```

Not sure if this is related to all the Hibernate 6 changes. Just checking here if it might be a bug.

**Comment by vladmihalcea** [comment]
Try using the StringArrayType instead and pass a String array and see if it works.

**Comment by dirkluijk** [comment]
Nice, that did the trick!

```kotlin
cb.equal(cb.literal(value), cb.function("any", StringArrayType::class.java, path))
```

Thanks! I hope this answer might help out others with the same issue. Thanks for the quick response!

**Comment by vladmihalcea** [comment]
@dirkluijk I'm glad I could help.

**Comment by dirkluijk** [comment]
I am sorry, I think I messed up. It seems not to be working. Sorry :(

**Comment by dirkluijk** [comment]
It seems that Hibernates uses the `CollectionJavaType.getRecommendedJdbcType()` which returns null.

**Comment by vladmihalcea** [comment]
In that case, you will need to debug it and see what's needed to make it work.

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was sent with the fix.
