### ISSUE TITLE
Add a FloatArrayType to map float[] as JPA entity properties

### ISSUE THREAD

**Issue by andreas-eberle** [vladmihalcea/hypersistence-utils#606]
Could you add a FloatArrayType like there is a DoubleArrayType?

**Comment by vladmihalcea** [comment]
@andreas-eberle Send me a Pull Request with the change request and I'll integrate it if runs properly.

**Comment by andreas-eberle** [comment]
I'm currently trying to get it to run locally. I basically copied the DoubleArrayType and switched everything to use Float. However, I get an error where it says I would need to implement `forEachJdbcType`. But the DoubleArrayType does not do that either. Do you have an idea what's wrong?

**Comment by vladmihalcea** [comment]
No, I don't know why you get that issue.

**Comment by vladmihalcea** [comment]
Fixed.
