### ISSUE TITLE
BatchSequenceGenerator should be able to search the DB sequence in the default schema

### ISSUE THREAD

**Issue by eazrael** [vladmihalcea/hypersistence-utils#613]
When using BatchSequenceGenerator sequences are not searched in the default schema configured for the connection. You have to hard code the schema into the sequence name in the annotation. 
For example. if there is a sequence called my_test_seq in schema my_schema, you have to write 

```
    @GenericGenerator(name = "id_seq", strategy = "io.hypersistence.utils.hibernate.id.BatchSequenceGenerator", parameters = {
            @Parameter(name = "sequence", value = "myschema.my_test_seq"),
            @Parameter(name = "fetch_size", value = "100") })

```
and cannot omit my_schema even if my_schema is the default schema set for the connection. Hibernate's own sequence generator will find the sequence without giving the schema name. 

I implemented that for Hibernate 6.0 and 6.2 in pull request https://github.com/vladmihalcea/hypersistence-utils/pull/611

**Comment by vladmihalcea** [comment]
This is a very useful improvement

**Comment by vladmihalcea** [comment]
Fixed.
