### ISSUE TITLE
BatchSequenceGenerator should use PostgreSQL generate_series to speed up ID generation

### ISSUE THREAD

**Issue by eazrael** [vladmihalcea/hypersistence-utils#614]
Replacing the recursive CTE 
```
WITH RECURSIVE t(n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1
    FROM t
    WHERE n < ?)
    SELECT nextval('your_sequence') FROM t
```
with 
`SELECT nextval('your_sequence') FROM generate_series(1, ?)`
halves execution time on PostgreSQL. 

Implemented in https://github.com/vladmihalcea/hypersistence-utils/pull/612.

Not a big improvement, but a cheap change.

**Comment by vladmihalcea** [comment]
Fixed.
