### ISSUE TITLE
'empty' period causes NullPointerException in Range<ZonedDateTime>

### ISSUE THREAD

**Issue by icorne** [vladmihalcea/hypersistence-utils#622]
When a period has the string value 'empty' Range<ZonedDateTime> does not handle this.
It causes a NPE

**Comment by icorne** [comment]
https://github.com/vladmihalcea/hypersistence-utils/compare/master...icorne:hypersistence-utils:master

As you can see here.
I wonder how we'd handle this, as empty ranges don't have timezone information..

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request that fixes the issue.

**Comment by vladmihalcea** [comment]
Fixed.
