### ISSUE TITLE
Make HibernateTypesContributor configurable so that we can enable or disable the automatic Type registration

### ISSUE THREAD

**Issue by xehonk** [vladmihalcea/hypersistence-utils#623]
It would be useful to be able to include only some (or no) default types via the HibernateTypesContributor. I would like to include the library to use JsonType but do not want to use PostgreSQLIntervalType. With the current setup this is not possible, because PostgreSQLIntervalType is set up as default for Duration fields.

Ideas:
- add a configuration that disables the HibernateTypesContributor entirely

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request that adds that configuration.

**Comment by vladmihalcea** [comment]
Fixed.
