### ISSUE TITLE
PostgreSQLEnumType returnedClass should be the Enum-specific class

### ISSUE THREAD

**Issue by joggeli34** [vladmihalcea/hypersistence-utils#627]
With hibernate 6.2 jpql queries which uses an enum as a parameter for a new class, the type matching is failing.

This happens because the returned class currently is "Enum" and not the specific enum type.

So it would work correctly when the returnedClass() is overriden by:

```java
    @Override
    public Class<Enum> returnedClass() {
        if (enumType != null) {
            return enumType.returnedClass();
        }
        return super.returnedClass();
    }
```

**Comment by vladmihalcea** [comment]
@joggeli34 We need a replicating test case for this issue so that we can see the test case succeeding after the fix.

**Comment by vladmihalcea** [comment]
Fixed.
