### ISSUE TITLE
SQLExtractor returns JPQL instead of SQL

### ISSUE THREAD

**Issue by ana-oleski** [vladmihalcea/hypersistence-utils#629]
Salut @vladmihalcea ,

I was using the SQLExtractor from hibernate-types-55   as described in https://vladmihalcea.com/get-sql-from-jpql-or-criteria/ 

I've updated to hibernate 6.2 and hypersistence-utils-hibernate-62 and I've noticed  the code is now returning JPQL instead of SQL.

Not sure there's anything you can do about ist but I thought I'd ask :-)

Ana

**Comment by vladmihalcea** [comment]
Try to investigate how it needs to be changed so that it will return the SQL query.

**Comment by vladmihalcea** [comment]
Fixed.
