### ISSUE TITLE
Implement EnhancedUserType in a new DescriptorImmutableType in Hibernate 6 modules

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-utils#633]
The `ImmutableType` should implement the `EnhancedUserType` in Hibernate 6.2.

If this issue is implemented, it will have to add support for `EnhancedUserType` for all Types that now extend `ImmutableType`.

**Comment by vladmihalcea** [comment]
This issue will be integrated when **ALL*  Types that now extend `ImmutableType` and `MutableType` will implement the `fromStringValue` from `EnhancedUserType`.

I won't have the time to implement it for all Types, but if this is important to you, then you should check out [this branch](https://github.com/vladmihalcea/hypersistence-utils/tree/enhanced) and continue overriding the `fromStringValue` for each Type that extends `ImmutableType` and `MutableType`.

When all the work is done, I will integrate it.

**Comment by L00kian** [comment]
I can try and make it a weekend project, any objections? :)

@vladmihalcea @piotrp

**Comment by piotrp** [comment]
Please go ahead. I wanted to try doing it, but it became larger than I have time for.

I think that `toString`/`fromStringValue` should be implemented by delegating them to appropriate types, which would leave `toSqlLiteral`. That too could be delegated, but unfortunately `UserType` doesn't provide enough information to do this.

```java
    @Override
    public String toSqlLiteral(T value) {
        // Type interface provides dialect and wrapper to toSqlLiteral, but UserType doesn't...
        return getJdbcTypeDescriptor().getJdbcLiteralFormatter(getJavaTypeDescriptor()).toJdbcLiteral(value, Dialect, WrapperOptions);
    }

    @Override
    public String toString(T value) throws HibernateException {
        return getJavaTypeDescriptor().toString(value);
    }

    @Override
    public T fromStringValue(CharSequence sequence) throws HibernateException {
        return getJavaTypeDescriptor().fromString(sequence);
    }
```

**Comment by vladmihalcea** [comment]
Probably the best way to handle it is to see how the Hibernate core Types implement them.

Most Hibernate core Types use the JDBC and Java descriptors, but implementing all that in the Hibernate 6.2 module is going to be a lot of work.

**Comment by L00kian** [comment]
I am puzzled, the original issue was there due to absence of `toSqlLiteral` signature in the `UserType` interface. However I'd still like to cover with tests all the new methods for the types affected. Any chance you got an insight what the method `fromStringValue` could used for in Hibernate (i.e what should be covered with the test)?

From what I could gather - it's used to work with discriminator column and discriminator values, but the column must be of type: String, Char or Integer which kinda doesn't go well with all the `UserType`s.

**Comment by vladmihalcea** [comment]
> I am puzzled, the original issue was there due to absence of toSqlLiteral signature in the UserType interface.

The `UserType` interface has no `toSqlLiteral` method.

> Any chance you got an insight what the method fromStringValue could used for in Hibernate (i.e what should be covered with the test)?

The `fromStringValue` is from the `EnhancedUserType`, and according to the [JavaDoc](https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/usertype/EnhancedUserType.html#fromStringValue(java.lang.CharSequence)), it's goal is to:

> Consume the given string representation back into this types java form.

The `EnhancedUserType` interface has changed in Hibernate 6, and since it's been 4 years since I quit working on Hibernate, I have no idea why the core devs changed it and for what purpose.

You will have to see in the Hibernate core course code what it's used for and then you'll see what's the best way to implement it.

**Comment by vladmihalcea** [comment]
Only the `ImmutableType` should extend the `EnhancedUserType`, so I created a `DescriptorImmutableType` to make this transition easier.

However, previously the `YearMonth` Types were extending the ``MutableType`, and that's not correct since the `YearMonth` is immutable.
