### ISSUE TITLE
Receiver class io.hypersistence.utils.hibernate.type.array.internal.StringArrayTypeDescriptor does not define or inherit an implementation of the resolved method 'abstract org.hibernate.type.BasicType resolveType

### ISSUE THREAD

**Issue by srikant-mvs** [vladmihalcea/hypersistence-utils#635]
I am seeing the below message as WARN and the spring boot application fails to start

`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Receiver class io.hypersistence.utils.hibernate.type.array.internal.StringArrayTypeDescriptor does not define or inherit an implementation of the resolved method 'abstract org.hibernate.type.BasicType resolveType(org.hibernate.type.spi.TypeConfiguration, org.hibernate.dialect.Dialect, org.hibernate.type.BasicType, org.hibernate.tool.schema.extract.spi.ColumnTypeInformation, org.hibernate.type.descriptor.jdbc.JdbcTypeIndicators)' of interface org.hibernate.type.descriptor.java.BasicPluralJavaType.`

I am using `io.hypersistence.utils.hibernate.type.json.JsonBinaryType` in my application and its part of a library. `StringArrayTypeDescriptor `class is not referenced neither in the library nor in the application.

versions:
Spring Boot v3.0.6, Spring v6.0.8
Hibernate ORM core version 6.1.7.Final
hypersistence-utils-hibernate-60 3.4.3

Can you let me know why am I facing this issue ?

**Comment by vladmihalcea** [comment]
I don't know why you are facing this issue.

But, you can use the existing test cases to try to replicate it in this repository. At the moment, all project test cases run just fine.

**Comment by vladmihalcea** [comment]
Since the [`AbstractArrayTypeDescriptor`]https://github.com/vladmihalcea/hypersistence-utils/blob/d0a3f05eaf2880331793fe5067af1781426fb235/hypersistence-utils-hibernate-60/src/main/java/io/hypersistence/utils/hibernate/type/array/internal/AbstractArrayTypeDescriptor.java#L107) implements that method, I assume your issue is caused by a class loading problemo your side.

**Comment by srikant-mvs** [comment]
I was able to find the root cause of the issue and fix. There was property defined for maven plugin version with 3.0.5, but the underlying spring boot version was running with 3.0.6.
This issue was due to the version mismatch.

**Comment by vladmihalcea** [comment]
Thanks for letting me know
