### ISSUE TITLE
@TypeDef removed from the hibernate-core:6.2.2.Final

### ISSUE THREAD

**Issue by BobbyBui00** [vladmihalcea/hypersistence-utils#637]
@vladmihalcea thank you for your library. It has helped me a lot.
I am having an annotation like this @TypeDef(name = "json", typeClass = JsonBinaryType.class) and a reference like this @Type(type = "json"). what should be the alternative if this is not supported anymore with imports.

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

**Comment by vladmihalcea** [comment]
Check out [this section](https://github.com/vladmihalcea/hypersistence-utils#hibernate-6) of the README file.
