### ISSUE TITLE
The ESCAPE literal in the LIKE clause is not escaped and caused an "syntax error at end of input" error

### ISSUE THREAD

**Issue by jamesdh** [vladmihalcea/hypersistence-utils#638]
So we tried to update hypersistence-utils-hibernate yesterday from 3.4.1 to 3.5.0. We have a Spring Boot 3.1 project, with a repo that makes use of QueryDSL. Unfortunately we discovered a single, lone query that breaks somewhat mysteriously from the update. I narrowed it down to the update from 3.4.3 to 3.4.4, the former working as expected and the latter causing the resulting breakage: 

> org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select p1_0.id,p1_0.first_name,p1_0.last_name,p1_0.user_type from provider p1_0 where p1_0.user_type=? and lower(p1_0.last_name) like ? escape !] [ERROR: syntax error at end of input

I've included a sample project at https://github.com/jamesdh/hypersistence-bug-633 that exposes the issue. Just run `gradle test` and you'll see the result. If you go into build.gradle and toggle the hypersistence dependency to 3.4.3, you'll see then that the test passes. 

Since 3.4.4 only contained a single update, it can be assumed the issue is somewhere within this commit: https://github.com/vladmihalcea/hypersistence-utils/commit/5fe3d3b7102abd5e3b63694b45a6c16125cc269e

See also #633

**Comment by jamesdh** [comment]
Does that ring any bells @vladmihalcea? I'm looking at your commit [here](https://github.com/vladmihalcea/hypersistence-utils/commit/5fe3d3b7102abd5e3b63694b45a6c16125cc269e) as that introduced this issue, but it's all a bit over my head unfortunately...

**Comment by vladmihalcea** [comment]
Maybe it's a Hibernate issue. You should discuss it on the Hibernate forum to see whether it's not a problem in Hibernate core.

**Comment by adamzr** [comment]
We are experiencing the same issue after the Spring 3.1 upgrade.

**Comment by vladmihalcea** [comment]
@adamzr Try to debug it and see how it could be fixed.

**Comment by jamesdh** [comment]
I found [HHH-16401](https://hibernate.atlassian.net/browse/HHH-16401) where a user reported similar issues, which resulted from them implementing JdbcType when they should have used VarCharType: 

> So turns out I am an idiot. I Overwrote the VARCHAR Type and with the new Hibernate Type system instead of extending the VarCharType i just made it implement JdbcType. Thats why Hibernate did not escape my string, its kind of surpising that it even worked that well

**Comment by vladmihalcea** [comment]
@jamesdh It's due to the `NullableCharacter` as it now implements the `EnhancedUserType`.

The easiest workaround is to use the `HibernateTypesContributor` to skip the registration of the `NullableCharacter`.

You can either disable the auto-register:

    hypersistence.utils.enable_types_contributor=false

Or use the `hypersistence.utils.types_contributor_filter` to filter just the `NullableCharacter`.

**Comment by jamesdh** [comment]
@vladmihalcea thank you for taking the time to look into this!

**Comment by vladmihalcea** [comment]
@jamesdh You're welcome.
