### ISSUE TITLE
Use com.vladmihalcea.hibernate.type.array.ListArrayType with Jackson 2.15.2

### ISSUE THREAD

**Issue by firstpostt** [vladmihalcea/hypersistence-utils#639]
Hi,
I have updated jackson core, jackson databind, jackson annotation dependencies from 2.13.5 to 2.15.2

Now I get the below error in DataJPATest:
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.vladmihalcea.hibernate.type.basic.NullableCharacterType

How do I solve this issue? This is in SpringBoot 2.7.12 application

**Comment by vladmihalcea** [comment]
Try switching to the latest version as you are using an old version that's no longer supported. Notice the "com.vladmihalcea". That's for version 2. Version 3 uses "io.hypersistence" instead.

**Comment by firstpostt** [comment]
Thanks. Now I have followed the readme file here https://github.com/vladmihalcea/hypersistence-utils/ and added below dependency:
<dependency>
      <groupId>io.hypersistence</groupId>
      <artifactId>hypersistence-utils-hibernate-55</artifactId>
      <version>3.5.0</version>
    </dependency>

I still get error:-
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.hypersistence.utils.hibernate.type.json.JsonType

**Comment by vladmihalcea** [comment]
I've just upgraded the Jackson XML Bind version to 2.15.2, and everything works just fine. Here's the [commit](https://github.com/vladmihalcea/hypersistence-utils/commit/d9de3cf94a0c2b6665ca5e95dd19ddd1a73fe276) for you to test it as well.
