### ISSUE TITLE
JSONB PostgresSQL Spring JPA

### ISSUE THREAD

**Issue by TimothyL96** [vladmihalcea/hypersistence-utils#640]
Hi, following the link in readme: https://vladmihalcea.com/jpa-query-setparameter-hibernate/

Is there an alternative solution when using Spring @Query ? Currently on Spring boot 3 + Hibernate 6 + PostgreSQL

I used `@Type(JsonBinaryType.class)` with the property type as generic `Object` but I'm getting the cannot convert bytea error. Removed all the TypeDefs annotation too.

**Comment by vladmihalcea** [comment]
You need to convert the Query method to a custom Repository method that allows you to call setParameter. 

Check out [this article](https://vladmihalcea.com/custom-spring-data-repository/) for more details about custom Repository methods.
