### ISSUE TITLE
Postgres JsonType for Strings are broken on Hibernate 55

### ISSUE THREAD

**Issue by cmdjulian** [vladmihalcea/hypersistence-utils#646]
**Describe the bug**
I have the following entity:

```java
@TypeDef(name = "jsonb", typeClass = JsonType.class)
package irrelevant;

import io.hypersistence.utils.hibernate.type.json.JsonType;
import org.hibernate.annotations.TypeDef;
```

```kotlin
@Entity
@DiscriminatorValue("STRING")
class StringFeature(
    id: Long? = null,
    @Type(type = "jsonb") @Column(name = "value_local_static", columnDefinition = "jsonb") override var valueLocalStatic: String?,
    @Type(type = "jsonb") @Column(name = "value_inherited_static", columnDefinition = "jsonb") override var valueInheritedStatic: String? = null
) : StaticFeature<String>(id)
```

This is my sql schema for that table:

```sql
CREATE TABLE IF NOT EXISTS feature
(
    id                     BIGINT      NOT NULL PRIMARY KEY,
    value_type             VARCHAR(32) NOT NULL,
    value_local_static     JSONB,
    value_inherited_static JSONB
);
```

When trying to persist my entity I get a sql syntax error. `org.postgresql.util.PSQLException: ERROR: invalid input syntax for type json
  Detail: Token "Test" is invalid.
  Wobei: JSON data, line 1: Test
unnamed portal parameter $7 = '...'`

The problem seems to be, that for String values Postgres JsonType expects the value to be quoted or transformed via `to_jsonb()`, which it is not. So instead of passing `Test`, the passed string should have been `"Test"`. After debugging for a while I found out that `ObjectMapperJsonSerializer` in its clone method just returns the String as it is. When changing that via force return in my ide to the quoted string, it works as intended. However, I'm not sure about the consequences of changing the clone method here, as I dont know what are the ripple effects for other jdbc drivers or database dialects. 

**Expected behavior**
No syntax error

**Additional context**
 - io.hypersistence:hypersistence-utils-hibernate-55:3.5.1
 - org.postgresql:postgresql:42.6.0
 - Spring Boot 2.7.14
 - Postgres 15

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request that fixes the issue.

**Comment by cmdjulian** [comment]
Some guidance would be nice, if just changing the clone method is a suitable fix, sure, I can do that. 
Would do you think? Seems like mariadb seems to work fine without quotes.

**Comment by vladmihalcea** [comment]
@cmdjulian You should first use the existing test cases as a reference to try to replicate the issue.

If you cannot replicate it in this repository, then the problem might originate somewhere else in your stack.

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was sent.
