### ISSUE TITLE
hibernate/type/utils/Configuration.java not loading 'hibernate.cfg.xml' properties | QUERY

### ISSUE THREAD

**Issue by Sawa-i** [vladmihalcea/hypersistence-utils#648]
Added 'ObjectMapperSupplier' path property in hibernate.cfg.xml so it could be used while initializing Configuration.java ( which would be used by JsonConfiguration.java to create 'ObjectMapperWrapper' )
i.e.

`<property name = "hypersistence.utils.jackson.object.mapper">com.transportial.utils.HibernateObjectMapperSupplier</property>
`

hibernate.cfg.xml properties seems to be added in 'serviceRegistry' variable but are not passed onto Configuration.java class, nor are loaded through its load() function ( which seems to load only application.properties and hibernate.properties)

**Note:** 'hibernate.properties' file when created and this property is added, is loaded into Configuration.java (as intended by load() function).

**Query:** Is 'hibernate.cfg.xml' property not yet meant to be passed into Configuration.java or am I missing something?

**Package:** "hypersistence-utils-hibernate-52" & "hypersistence-utils-hibernate-55", version : 3.5.0

**Comment by vladmihalcea** [comment]
Since Hibernate 5.5, the properties can be passed directly to the Types. For instance, add a break point [here](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-55/src/main/java/io/hypersistence/utils/hibernate/type/json/JsonType.java#L85) if you're using `JsonType`. All the properties will be passed no matter how they were declared.

For Hibernate 5.2 or older version, you can pass the properties via the legacy `hibernate.cfg.xml` file, but you can do it via the `hibernate.properties` one.

**Comment by Sawa-i** [comment]
Hi @vladmihalcea, Thanks for answering my query.

**Quick Question:** Would 'hibernate.cfg.xml' properties ever going to be passed on like 'hibernate.properties' or through '`serviceRegistry`' (as `org.hibernate.cfg.Configuration` already configured with hibernate.cfg.xml resource)? 

Also as hibernate.cfg.xml contains whole hibernate configuration including properties already.

**Comment by Sawa-i** [comment]
Application's not that much old, like around 1-2 years. Using hibernate 5.2 and java 11.

**Comment by vladmihalcea** [comment]
Using legacy configs, mismatching dependencies, it really looks like your company could benefit from my [consulting](https://vladmihalcea.com/consulting/). 

After reviewing your app, I'll show you how to get the best out of it and help your company avoid some mistakes that could could cost your company a lot in the long term.

**Comment by Sawa-i** [comment]
But is it really that much old, I thought hibernate.cfg.xml is supposed to be one whole comprehensive configuration file for hibernate while hibernate.properties only for properties.

I couldn't find any concerns revolving around hibernate.cfg.xml according to my findings.

Your comment is a bit worrisome 😅 so I am interested what could be potential problems that we could be missing.

**Comment by vladmihalcea** [comment]
For a glimpse of what you might br missing, add [Hypersistence Optimizer](https://vladmihalcea.com/hypersistence-optimizer/) to your project and check out what issues it finds.
