### ISSUE TITLE
Adds support for using MonetaryAmount in @ElementCollection

### ISSUE THREAD

**Issue by Sarrruman** [vladmihalcea/hypersistence-utils#652]
Entity X containing @ElementCollection of type Y, where Y has a field of type _MonetaryAmount_, does not pass Hibernate's "metadata building" phase and raises following exception:

`org.hibernate.MappingException: Could not instantiate collection persister implementor org.hibernate.persister.collection.BasicCollectionPersister for collection-role ...`

**Comment by Sarrruman** [comment]
```
    @Entity(name = "Salary")
    @Table(name = "salary")
    public static class Salary {
        @Id
        @GeneratedValue
        private long id;

        private String other;

        @ElementCollection
        private List<SalaryComponent> components = new ArrayList<>();

        public long getId() {
            return id;
        }

        public void setId(long id) {
            this.id = id;
        }

        public List<SalaryComponent> getComponents() {
            return components;
        }

        public String getOther() {
            return other;
        }

        public void setOther(String other) {
            this.other = other;
        }
    }

    @Embeddable
    public static class SalaryComponent {
        @AttributeOverride(name = "amount", column = @Column(name = "salary_amount"))
        @AttributeOverride(name = "currency", column = @Column(name = "salary_currency"))
        @CompositeType(MonetaryAmountType.class)
        private MonetaryAmount value;

        public SalaryComponent(MonetaryAmount value) {
            this.value = value;
        }

        public SalaryComponent() {

        }

        public MonetaryAmount getValue() {
            return value;
        }

        public void setValue(MonetaryAmount value) {
            this.value = value;
        }
    }
```

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request that fixes the issue.

**Comment by Sarrruman** [comment]
Exception is raised because `org.hibernate.cfg.PropertyContainer`, which is responsible for the creation of metadata for the `@Embeddable` class, incorrectly constructs metadata for the embeddable type, because `MonetaryAmountMapper` doesn’t have getters&setters for its fields. 

`org.hibernate.cfg.PropertyContainer`'s contstructor is getting passed **DEFAULT** for _defaultClassLevelAccessType_ parameter, which is then set to `AccessType.PROPERTY`, which results in `PropertyContainer`’s constructor relying on getters, instead of fields, for populating `persistingAttributes`. 

In other cases (non-@ElementCollection ones), `AccessLevel.FIELD` is being passed in, thus not requiring `MonetaryAmountMapper`’s getters and resulting in correct mapping by Hibernate.

**Comment by vladmihalcea** [comment]
As I explained in my [High-Performance Java Persistence book](https://vladmihalcea.com/books/high-performance-java-persistence/), `@ElementCollection` is a bad idea anyway.

So, you are better off using a bidirectional one-to-many where the MonetaryAmount is just a basic property in the child entity.

**Comment by Sarrruman** [comment]
I have a specific use-case: list, very short one, of value objects - something similar to the example I created in test `PostgreSQLMonetaryAmountTypeElementCollectionTest`: Salary that is comprised of a couple of value components. They don't have their id etc..

**Comment by vladmihalcea** [comment]
Fixed.
