### ISSUE TITLE
Add a hypersistence-utils-hibernate-63 module for Hibernate 6.3

### ISSUE THREAD

**Issue by devendraPatidar1** [vladmihalcea/hypersistence-utils#657]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

`  io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.setParameterValues(PostgreSQLEnumType.java:56)`

The following method did not exist:

`org.hibernate.metamodel.model.convert.spi.EnumValueConverter org.hibernate.type.EnumType.getEnumValueConverter()`

**Comment by vladmihalcea** [comment]
Hibernate 6.3 is not supported yet. Feel free to implement it and send me a Pull Request when you are done.

**Comment by oliveryasuna** [comment]
@vladmihalcea Are you no longer contributing to the project?

**Comment by milgner** [comment]
Just FYI for anyone stumbling over this: Hibernate 6.3 has native support for PostgreSQL enums. Just use

```kotlin
@JdbcType(PostgreSQLEnumJdbcType::class)
val myEnum: MyEnum
```

I still use hypersistence-utils for PostgreSQL interval types - it's great! - but for enums it is not required anymore.

**Comment by vladmihalcea** [comment]
@oliveryasuna Over the next few years, I will be very busy and won't have too much spare time to work on this project.

However, if you provide a Pull Request with the fix, I will find some time to review and integrate it. Looking forward to your contributions.

**Comment by benstpierre** [comment]
We could really use a hibernate 6.3 compatible version.  I don't think I have the skills with hibernate's internals to make it happen.  Hopefully some kind soul with the skills does!

**Comment by milgner** [comment]
The question is: what would need to be done?

Apart from removing enum support from hypersistence-utils (as it's not required anymore thanks to built-in support), is there anything that requires actual changes for Hibernate 6.3?
If it's only removal of that thing, it's much less important as this is a trivial and mostly cosmetic / clean-up kind of change.

As mentioned, I'm only using hypersistence `Interval` types and these work just fine with Hibernate 6.3.

**Comment by vladmihalcea** [comment]
Here's what's needed to be done:

1. Create a new 63 module by copying the 62 one
2. Set the Hibernate version to 6.3
3. Run the tests and fix everything so that all tests pass

That's it.

**Comment by oliveryasuna** [comment]
@benstpierre @milgner @vladmihalcea A discussion should be had on whether enum support should be removed from hypersistence-utils or updated to support Hibernate 6.3.

In no particular order...

**Argument 1: Update hypersistence-utils to support Hibernate 6.3's enum**
1. **Backwards compatibility:** Maintaining hypersistence-utils and making it compatible with Hibernate 6.3 can help us preserve backwards compatibility. Existing projects that rely on hypersistence-utils for enum support can upgrade to Hibernate 6.3 and hypersistence-utils-hibernate-63 without refactoring their existing implementations or experiencing disruptions.
2. **Uniformity:** Updating hypersistence-utils would offer uniformity to projects that span multiple Hibernate versions, where native enum support might not be available. Developers working on projects that have not upgraded to Hibernate 6.3 would still have a consistent approach to handled enums (and when they upgrade to Hibernate 6.3).
3. **Customization & control:** Not sure, but if hypersistence-utils offers customization, or additional features or behaviors related to enums that are not present in Hibernate's native support, maintaining support can preserve these features for projects that rely on them.

**Argument **2: Drop enum support in favor of Hibernate's native support**
1. **Reduced maintenance overhead:** Relying on HIbernate's native support can reduce the maintenance overhead associated with keeping hypersistence-utils up-to-date with the latest Hibernate versions, allowing developers to focus more on feature development.
2. **Performance & optimization:** A benchmark should be performed. Native support for enums might be more optimized and performant, as it is built into Hibernate itself. It could offer better integration and leverage internal optimizations, benefiting applications in terms of performance and resource usage.
3. **Standardization:** Adopting Hibernate's native support for enums could standardize the way developers handle enums, making it easier to share knowledge, find solutions, and get community support. By dropping enum support in favor of Hibernate's native support, we would push towards this goal.

I would love to hear from @thjanssen.

**Comment by vladmihalcea** [comment]
The PostgreSQL Enum Type in Hypersistence Utils does not do anything special.

If the Hibernate 6 provides support for it, then the current Type should be deprecated in the 60 snd 62 modules and removed in the new 63 module. Most likely that a new module will be needed.

**Comment by adiinfo-77** [comment]
Hi

i just discovered this wonderful project today and used it for getting the native Query generated by PSQL.
Something like:
String nativeSql = SQLExtractor.from(query);

i can confirm that Hibernate 6.3 does not work: i also get an exception "contains compatible versions ..." and had to revert to 6.2.9.

So it is definitely not only about PostgreSQL Enum's.

Andrej

**Comment by milgner** [comment]
> i can confirm that Hibernate 6.3 does not work: i also get an exception "contains compatible versions ..." and had to revert to 6.2.9.
> 

Could you add the full error message and stacktrace here? That would certainly help to get a full picture of what needs to be done.

**Comment by vladmihalcea** [comment]
@milgner From the previous Hibernate 6 modules, there are surely tons of things that have to be done. 

You can use [this branch](https://github.com/vladmihalcea/hypersistence-utils/tree/63) as a starting point, and if you run `mvn clean test-compile`, here's a list of issues that have to be fixed first:

```
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\PostgreSQLEnumType.java:[10,55] error: cannot find symbol
[ERROR]   symbol:   class NamedEnumValueConverter
[ERROR]   location: package org.hibernate.type.descriptor.converter.internal
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\MutableDynamicParameterizedType.java:[14,7] error: MutableDynamicParameterizedType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR]   where T is a type-variable:
[ERROR]     T extends Object declared in class MutableDynamicParameterizedType
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\ZoneIdType.java:[17,7] error: ZoneIdType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\YearMonthEpochType.java:[17,7] error: YearMonthEpochType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\MonthDayIntegerType.java:[16,7] error: MonthDayIntegerType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\YearMonthIntegerType.java:[18,7] error: YearMonthIntegerType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\Iso8601MonthType.java:[18,7] error: Iso8601MonthType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\MonthDayDateType.java:[19,7] error: MonthDayDateType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\YearMonthTimestampType.java:[17,7] error: YearMonthTimestampType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\YearMonthDateType.java:[18,7] error: YearMonthDateType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\PostgreSQLEnumType.java:[52,16] error: cannot find symbol
[ERROR]   symbol:   class NamedEnumValueConverter
[ERROR]   location: class PostgreSQLEnumType
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\basic\YearType.java:[19,7] error: YearType is not abstract and does not override abstract method getSqmType() in SqmExpressible
[ERROR] hypersistence-utils\hypersistence-utils-hibernate-63\src\main\java\io\hypersistence\utils\hibernate\type\money\CurrencyUnitType.java:[15,7] error: CurrencyUnitType is not abstract and does not override abstract method getSqmType() in SqmExpressible
```

However, this is just to compile the project. When you will be done with that, there are tests that might be failing too, and those will have to be fixed as well.

**Comment by adiinfo-77** [comment]
@milgner

here is the stacktrace i get when using Hibernate 6.3.1:

Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.hibernate.query.spi.QueryEngine, but class was expected
	at io.hypersistence.utils.hibernate.query.SQLExtractor.from(SQLExtractor.java:46)
	at hibernatetest.hibernatejpa1.HibernateJPA1.main(HibernateJPA1.java:95)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:1000)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:947)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:471)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)

**Comment by mlinhard** [comment]
What worked for me on Spring Boot 3.1.4, Hibernate 6.3.1 is

```java
    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "my_postgres_enum_type_name")
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    MyJavaEnumName field;
````

**Comment by dreis2211** [comment]
More an FYI: Since Spring-Boot 3.2 Hibernate 6.3 is included. Which makes this library not compatible anymore with newer Spring-Boot versions starting with 3.2. that was released today...

**Comment by vladmihalcea** [comment]
@dreis2211 It will be compatible when this issue is fixed. Looking forward to the Pull Request that fixes it.

**Comment by dreis2211** [comment]
Based on the comment here, it might make sense to directly go to Hibernate 6.4: https://hibernate.atlassian.net/browse/HHH-17454?focusedCommentId=113382

**Comment by adrianAzoitei** [comment]
> @dreis2211 It will be compatible when this issue is fixed. Looking forward to the Pull Request that fixes it.

@vladmihalcea  should we then use Spring 6.1.x in the new `hypersistence-utils-hibernate-63` project?

**Comment by tmvlpl** [comment]
All in all the necessary code changes to make it compile and test successfully with Hibernate 6.3 were small. As I don't use most of the libraries features I have no proper real world test case for the changes. So please try out the changes and report any issues.

**Comment by vladmihalcea** [comment]
Fixed.
