### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: operator does not exist: status_enum = character varying exception after migrating Spring 3 with Hibernate 6.3.1 

### ISSUE THREAD

**Issue by JotDakha** [vladmihalcea/hypersistence-utils#660]
@vladmihalcea Earlier I was using  **hibernate-types-52** library to support for **PostgreSQLEnumType** with Hibernate **@TypeDefs**. But after migration, **hypersistence-utils-hibernate** has been updated to support Postgres custom enum datatypes.

(looking for a solution and by referring to this ticket:-  https://github.com/vladmihalcea/hypersistence-utils/issues/514)
@Enumerated(EnumType.STRING)
@Column(columnDefinition = "status_enum")
@Type(PostgreSQLEnumType.class)
private Status status

exception getting - _Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: status_enum = character varying__
And if I am lowering the hibernate version to 6.2.9, then getting the exception.

_`Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [status] in table [user]; found ["status_enum" (Types#VARCHAR)], but expecting [status_enum (Types#OTHER)]`_
 
 Attaching ticket opened with hibernate team - https://discourse.hibernate.org/t/cannot-invoke-org-hibernate-boot-spi-metadatabuildingcontext-getmetadatacollector-because-this-metadatabuildingcontext-is-null/8298
 
 Please suggest to resolve this issue or let me know if I missed any steps.

**Comment by vladmihalcea** [comment]
Hibernate 6.3 support should be implemented via #657.

If you need this feature, then you should definitely send me a Pull Request with the fix. I won't have the time to implement it, but I could review it when you are done.
