### ISSUE TITLE
JsonType not working for Postgres native query

### ISSUE THREAD

**Issue by Spandy122** [vladmihalcea/hypersistence-utils#662]
JsonType not working , getting "Could not determine recommended JdbcType for" error when inserting the data into jsonb column's using native query. Using Java 17 with spring boot version 3.1.0, Hibernate 6.2.2.Final , postgresql 12 and 
Using hypersistence-utils-hibernate-62 version 3.5.3

  @Type(JsonType.class)
  @Column(columnDefinition="jsonb")
  private EnrichExpn expn;

  @Type(JsonType.class)
  @Column(columnDefinition="jsonb")
  private EnrichExpnScratch expnScratch;

  Native query :
  String query = "INSERT INTO cust_enrich(cust_id, correlation_id, expn, expn_scratch)                     
  values(:cust_id, :correlation_id, :expn, :expn_scratch) ON CONFLICT DO NOTHING "

  var queryRun =
          entityManager
              .createNativeQuery(query)
              .unwrap(Query.class)
              .setParameter("cust_id", t.getCustId())
              .setParameter("correlation_id", t.getCorrelationId())
              .setParameter("expn", t.getExpn(), JsonType.INSTANCE)
              .setParameter("expn_scratch", t.getExpnScratch(), JsonType.INSTANCE);
queryRun.executeUpdate();

**Comment by vladmihalcea** [comment]
Check out [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-62/src/test/java/io/hypersistence/utils/hibernate/type/json/generic/GenericPostgreSQLJsonTypeTest.java#L107) for a solution.
