### ISSUE TITLE
Range overlap method

### ISSUE THREAD

**Issue by lbruun** [vladmihalcea/hypersistence-utils#664]
This is an enhancement request to add a new convenience method to the `Range` class, namely an `overlaps` boolean method:

```java
/**
* Tests if there is any overlap between this range and the range in the argument.
*
* assertTrue(integerRange("[-12,10]").overlaps(integerRange("[7,20]")))
* assertTrue(integerRange("[-12,10]").overlaps(integerRange("[10,20]")))
* assertTrue(integerRange("(,)").overlaps(integerRange("(,)"))
*
* assertFalse(integerRange("[-12,10]").overlaps(integerRange("[11,20]")))
* assertFalse(integerRange("(,10]").overlaps(integerRange("[11,20]")))
*/
boolean overlaps(Range<T> range)
```
Another method name for this might be `hasIntersection()`. Dunno.  

Implementation is trivial. PR coming up. 

Also: I would clarify on the existing [contains(otherRange) method](https://javadoc.io/static/io.hypersistence/hypersistence-utils-hibernate-62/3.5.3/io/hypersistence/utils/hibernate/type/range/Range.html#contains(io.hypersistence.utils.hibernate.type.range.Range)) that it checks if the argument range is _fully_ included (fully contained) within the current range. .. which may be obvious from the word "contains", but wasn't to me. :-)

**Comment by vladmihalcea** [comment]
@lbruun If you think it's useful, then you can provide a Pull Request with that implementation. As for the `contains` method, I have no idea what the original contributor had in mind. You need to use the Git history to see who implemented the method and ask for more details.

**Comment by lbruun** [comment]
More info:  What I propose is the exact equivalent of PostgreSQL's `&&` operator.
In PostgreSQL you can do:

```sql
SELECT range1 && range2
```
... which returns a boolean. (true if there is any overlap between the two ranges)

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was provided for this.
