### ISSUE TITLE
What's replacement for TypeDef of jsonb?

### ISSUE THREAD

**Issue by harrythedev** [vladmihalcea/hypersistence-utils#665]
**No free-of-charge support**

Before you file an issue, note that there is **no free-of-charge support**. This project is Free, as in Libre, not Gratis.

As explained in the [README](https://github.com/vladmihalcea/hypersistence-utils#bug-fixes-and-enhancements) file, only if you purchase a Paid support plan, we will investigate and assist you with a problem.

Alternatively, you can file the issue, investigate the solution, and submit a Pull Request with a fix. However, due to lack of time, I can only review the submitted Pull Requests from time to time, so you may need to wait several months until the Pull Request is reviewed and integrated.

**Describe the bug**
I'm running into issues from newer version of hibernate (<artifactId>hypersistence-utils-hibernate-62</artifactId>). It seems like @TypeDef was deprecated. What would be the replacement for this?

**To Reproduce**

I have been using jsonb TypeDef but it's breaking after springboot upgrade. Here is what I used to have.

@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
someclass

@Type(type = "jsonb")
@Column

What would be the fix for this?

**Expected behavior**
Not getting compilation error

**Additional context**

**Comment by vladmihalcea** [comment]
The [README](https://github.com/vladmihalcea/hypersistence-utils#hibernate-6) file provides the answer to your question.
