### ISSUE TITLE
Postgresql JSONB double quoted error on persistence

### ISSUE THREAD

**Issue by codelpap** [vladmihalcea/hypersistence-utils#667]
Hi there.

Thanks for your contribution.

**Describe the bug**
I'm developing a grpc quarkus service and decided to use hypersistence-utils for mapping a JSONB field "items" in postgresql.

The entity mapping is as follows :

@Type(JsonBinaryType.class)
@Column(columnDefinition = "jsonb")
private List<OfferItem> items;

OfferItem is a simple Pojo. When i fetch data it works fine, but when i try to persist data, the data is saved as doubled quoted escape  string ? e.g. 

"[{\"quantity\":1,\"options\":[\"op1\",\"op2\"],\"description\":{\"id\":\"\",\"en\":\"val1\",\"el\":\"val2\"}},{\"quantity\":1,\"options\":[\"op1\",\"op2\"],\"description\":{\"id\":\"\",\"en\":\"val1\",\"el\":\"val2\"}}]" 

instead of

[{"quantity":1,"options":["op1","op2"],"description":{"id":"","en":"val1","el":"val2"}},{"quantity":1,"options":["op1","op2"],"description":{"id":"","en":"val1","el":"val2"}}]

**Expected behavior**
which is wrong. The expected behavior would be to save the latter to the database.

Project setup 
quarkus 3.2.2.Final
<jackson-databind>2.15.2</jackson-databind>
<jackson-core>2.12.5</jackson-core>
<artifactId>quarkus-hibernate-reactive-panache</artifactId>
<dependency>
    <groupId>io.hypersistence</groupId>
    <artifactId>hypersistence-utils-hibernate-62</artifactId>
    <version>3.6.0</version>
  </dependency>
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.15.2</version>
  </dependency>
.....

I understand the concept of "no free-of-charge support" but this looks like a bug. Any fix pointers will be highly appreciated, or at least consideration to fix in a next release.

Thank you very much. Regards

**Comment by vladmihalcea** [comment]
> I understand the concept of "no free-of-charge support" but this looks like a bug. 

When I was working as a software developer, I remember I was paid for fixing bugs. Do you imply that OSS is any different? 

Unlike commercial products, in OSS, you have two choices:

- you can fix the problem yourself
- you can pay someone to do it for you. You can even hire someone of Upwork to fix this problem if you don't want to do it.

> Any fix pointers will be highly appreciated:

The project has a [test folder](https://github.com/vladmihalcea/hypersistence-utils/tree/master/hypersistence-utils-hibernate-62/src/test/java/io/hypersistence/utils/hibernate/type/json) that's packed with examples showing you that persisting and fetching JSON works like a charm. Just compare the existing tests to yours and see why there's no escaping issue in the existing test cases.

> or at least consideration to fix in a next release.

It's all up to you. Be the change you want to see in this world.

**Comment by codelpap** [comment]
Thanks for replying.

**Comment by vladmihalcea** [comment]
@codelpap You're welcome. Looking forward to your Pull Request that fixes this issue.

**Comment by codelpap** [comment]
More on this issue. I've downloaded and ran successfully hypersistence-utils tests, especially PostgreSQLGenericJsonBinaryTypeTest. Everything looks fine. The data is stored correctly to the db. Furthermore i removed panache dependency from my quarkus reactive project (in any case). Unfortunately it still escapes the json string. Don't know exactly where to go from here, any ideas ?

**Comment by vladmihalcea** [comment]
Closed as no replicating test case was provided.
