### ISSUE TITLE
PostgreSQLRangeType must override toSqlLiteral()

### ISSUE THREAD

**Issue by lbruun** [vladmihalcea/hypersistence-utils#670]
The `PostgreSQLRangeType` class must override `toSqlLiteral()`.

At the moment you just get the default from `ImmutableType` which is:

```java
public String toSqlLiteral(T o) {
    return o != null ?
        String.format(Locale.ROOT, "'%s'", o) :
        null;
}
```

For the PostgreSQLRange type this certainly does not produce a SQL literal. (it produces the `toString()` representation of the Range value and this ain't no SQL literal)

Therefore specifically for `PostgreSQLRangeType`  it should be:

```java
@Override
public String toSqlLiteral(Range o) {
    return o.asString();
}
```

I believe the reason why this problem hasn't been discovered before is that it will only manifest itself when you try to use the Range type in a HQL function call. Most use cases of the this type probably just use the type "as is" in an Entity class which means the methods acting on a PrepararedStatement will be used .. and this works flawlessly.

**Comment by lbruun** [comment]
I've looked at it some more: It seems to be a common theme that sub-classes of `ImmutableType` do not override the `toSqlLiteral()` method. For example, I've also looked at `PostgreSQLIntervalType` which suffers from the same problem.

In conclusion:  At the moment the various sub-classes of `ImmutableType`  will potentially not work if you attempt to use them as parameter in a HQL function call.  They will only work if the value's `toString()`  happen to produce something the database can accept as a literal value for that particular column type.

**Comment by vladmihalcea** [comment]
Since you already investigated the issue, you should provide a Pull Request with the fix.

**Comment by lbruun** [comment]
Contributing is quite involved (time consuming) due to the many sub-modules in this repo (one for each Hibernate version).
So I will not contribute a PR at the moment.

I will, however, provide a workaround which works for my scenario, which is dynamically building queries with the JPA `CriteriaBuilder`. Here is my workaround:


```java
// Suppose myRangeValue is of type Range<Integer>  (or some other sub-type of Range class)

// This will not work because PostgreSQLRangeType.toSqlLiteral() does not produce correct value:
Expression<Range<Integer>> criteriaBuilder.literal(myRangeValue);
```

Instead treat it like a `String` literal:

```java
Expression<String> criteriaBuilder.literal(myRangeValue.asString());
```

This renders the value correctly in the SQL. It works because Hibernate already knows how to render a `String` value into a SQL literal. As you would expect it simply encloses the string value in single quotes.

**Comment by vladmihalcea** [comment]
Closed as there's a workaround and no fix was provided.
