### ISSUE TITLE
Return original object if target and original are the same when merging

### ISSUE THREAD

**Issue by SimoneGiusso** [vladmihalcea/hypersistence-utils#677]
**Describe the bug**
I was migrating from Spring Boot 2.7.x to Spring Boot 3.1.4 and one integration test was failing because a change of behaviour when calling the `EntityManager#merge` method on an entity which has a json property (JsonType.class) persisted and without changes between the call to `EntityManager#persist` and `EntityManager#merge`. The cause was due to the fact that `EntityManager#merge` was returning the entity but with a different reference for the json property compare to the one before calling the `merge` method.

Issue has started with `hypersistence-utils-hibernate-60`. 

**To Reproduce**

I created two simple spring projects to show the regression:

- Running this very simple [code](https://github.com/SimoneGiusso/hibernate-5-entity-manager-merge-method/blob/0d876bbb4081d58d247e2f42702a4cd3120b1726/src/main/java/com/simonegiusso/hibernate/service/NOPService.java#L20) will output [this](https://github.com/SimoneGiusso/hibernate-5-entity-manager-merge-method/blob/main/README.md). As you can see the hashcode of the wrapped value doesn't change. [hypersistence-utils-hibernate-55](https://github.com/SimoneGiusso/hibernate-5-entity-manager-merge-method/blob/0d876bbb4081d58d247e2f42702a4cd3120b1726/pom.xml#L38C16-L38C16) was used here.
-  Running the exactly same code with [hypersistence-utils-hibernate-62](https://github.com/SimoneGiusso/hibernate-6-entity-manager-merge-method/blob/73d8046ba4f34c66e8d1308ff16976ac3a63f5cb/pom.xml#L38) shows a different [behaviour](https://github.com/SimoneGiusso/hibernate-6-entity-manager-merge-method/blob/main/README.md). Now the hashcode of the `wrappedValue` changes after calling `merge`.

**Expected behavior**
The one showed in the first project.

**Additional context**
After further analysis I may found the change that caused the regression. Let's have a look at the `JsonType.java` class as an example. In version 5x [it](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-55/src/main/java/io/hypersistence/utils/hibernate/type/json/JsonType.java) inheritance from the hibernate class [AbstractSingleColumnStandardBasicType](https://github.com/vladmihalcea/hypersistence-utils/blob/f431f4b3c54da577b288fd70e13c6669bc6c5671/hypersistence-utils-hibernate-55/src/main/java/io/hypersistence/utils/hibernate/type/AbstractHibernateType.java#L13C56-L13C93), which inheritances this [replace](https://github.com/hibernate/hibernate-orm/blob/30241bbe9f2b3f87bde0d3473cdea642656d6b8c/hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java#L349) method. When this method is called, [here](https://github.com/hibernate/hibernate-orm/blob/30241bbe9f2b3f87bde0d3473cdea642656d6b8c/hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java#L74) a check is done: if original is equal to target do not make a deep copy but return the original.

Other the other and [JsonType.java now](https://github.com/vladmihalcea/hypersistence-utils/blob/f431f4b3c54da577b288fd70e13c6669bc6c5671/hypersistence-utils-hibernate-55/src/main/java/io/hypersistence/utils/hibernate/type/json/JsonType.java#L57) doesn't inheritance this [replace](https://github.com/hibernate/hibernate-orm/blob/42e7ce824992e820c1675b2cc89969c5cb1cf284/hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java#L315) method anymore (still available in recent versions of Hibernate).  This `replace` method is called in the hibernate `TypeHelper` class [here](https://github.com/hibernate/hibernate-orm/blob/42e7ce824992e820c1675b2cc89969c5cb1cf284/hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java#L88). Now this other hibernate [replace](https://github.com/hibernate/hibernate-orm/blob/42e7ce824992e820c1675b2cc89969c5cb1cf284/hibernate-core/src/main/java/org/hibernate/type/CustomType.java#L266) method is called which triggers the call to [replace](https://github.com/vladmihalcea/hypersistence-utils/blob/f431f4b3c54da577b288fd70e13c6669bc6c5671/hypersistence-utils-hibernate-62/src/main/java/io/hypersistence/utils/hibernate/type/MutableType.java#L128) method of this library where the previous check is not done anymore and a deepcopy is made. 

I do not know why has been decided that `JsonType.java` should not inheritance the `AbstractStandardBasicType` anymore.

**Comment by vladmihalcea** [comment]
@SimoneGiusso Since you already investigated this issue, you should provide a Pull Request with the fix. If all the tests are passing with your change, then we should definitely consider it.

**Comment by SimoneGiusso** [comment]
> @SimoneGiusso Since you already investigated this issue, you should provide a Pull Request with the fix. If all the tests are passing with your change, then we should definitely consider it.

@vladmihalcea [PR](https://github.com/vladmihalcea/hypersistence-utils/pull/678) is very small. Can you have a look?

**Comment by vladmihalcea** [comment]
I'll check it out when I have some time.

**Comment by vladmihalcea** [comment]
Fixed.
