### ISSUE TITLE
Support for custom converters in array types

### ISSUE THREAD

**Issue by Jeetah** [vladmihalcea/hypersistence-utils#679]
Currently custom Converters for enum like this one:

`@Converter(autoApply = true)
class StatusLevelConverter :
    EnumAttributeConverter<StatusLevel>(StatusLevel::class.java, { it?.state })`

are not supported for EnumArrayTypes - i.e. enums ins this arrays seem to be written always with their _toString()_ value. And read with the _valueOf()_. Which makes parsing a little inconvenient when we have enums with upper case names and e.g. different lower case values. The "solution" was to write the enum uppercase in DB with the name. And the drawback to use a different enum Jackson converter when using it e.g. in JSON output.
This would not be a problem if ArrayTypes would just consider custom converter for the contained objects.

**Comment by vladmihalcea** [comment]
Send a Pull Request with the fix and I'll check it out when I have some time.

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was sent.
