### ISSUE TITLE
PostgreSQLEnumType with Hibernate 6 is not working

### ISSUE THREAD

**Issue by rs10615** [vladmihalcea/hypersistence-utils#680]
<img width="886" alt="Screenshot 2023-12-02 at 2 36 48 PM" src="https://github.com/vladmihalcea/hypersistence-utils/assets/31204067/0f2ae918-24a5-49c4-9007-f2115d5e37e4">
@vladmihalcea I am running into an issue after migration of existing project to Spring Boot 3 and Java 17, I am using the following dependency . I would appreciate your help

implementation (group: 'com.vladmihalcea', name: 'hibernate-types-60', version: '2.20.0')

```

	@Enumerated(EnumType.STRING)
	@Column(columnDefinition = "import_status")
	@Type(PostgreSQLEnumType.class)
	private RMAFileStatusEnum importStatus;

```

**### The error Message I am getting on running the application is as -**

APPLICATION FAILED TO [START](<img width="886" alt="Screenshot 2023-12-02 at 2 36 48 PM" src="https://github.com/vladmihalcea/hypersistence-utils/assets/31204067/c4326b32-f084-4968-a939-68e14cdf9351">)

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

com.vladmihalcea.hibernate.type.basic.PostgreSQLEnumType.setParameterValues(PostgreSQLEnumType.java:54)
The following method did not exist:

`'org.hibernate.metamodel.model.convert.spi.EnumValueConverter org.hibernate.type.EnumType.getEnumValueConverter()'`

The calling method's class, com.vladmihalcea.hibernate.type.basic.PostgreSQLEnumType, was loaded from the following location:**

` jar:file:/Users/global/.gradle/caches/modules-2/files-2.1/com.vladmihalcea/hibernate-types-60/2.20.0/b56eced44eb94e20cc71e5a0367885df9c099cae/hibernate-types-60-2.20.0.jar!/com/vladmihalcea/hibernate/type/basic/PostgreSQLEnumType.class`

Investigation-
What i have noticed that `import org.hibernate.metamodel.model.convert.spi.EnumValueConverter;` in the class the `PostgreSQLEnumType 
 ` is having trouble with package  `convert`. I guess it has been removed.

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request that fixes it.
