### ISSUE TITLE
Oracle Interval Type does not support negative intervals

### ISSUE THREAD

**Issue by lorenzbaier** [vladmihalcea/hypersistence-utils#682]
**Describe the bug**
Oracle Interval Type cant handle negative duration like "PT-13H-5M". 

**To Reproduce**
Save duration "PT-13H-5M" -> error invalid interval.
Same issue when loading -> does not match regex with leading minus sign.

**Expected behavior**
Negative interval should be parsed to `INTERVAL '-0 13:05:00' DAY TO SECOND`  instead of `INTERVAL '0 -13:-05:00' DAY TO SECOND`

**Comment by vladmihalcea** [comment]
Fixed.
