### ISSUE TITLE
PostgreSQLEnumType not supported on the hypersistence-utils-hibernate-63 lib

### ISSUE THREAD

**Issue by brandonfl** [vladmihalcea/hypersistence-utils#689]
**Describe the bug**

`hypersistence-utils-hibernate-63` not supporting `PostgreSQLEnumType`

**To Reproduce**

Import `hypersistence-utils-hibernate-63` 

```
implementation(group: 'io.hypersistence', name: 'hypersistence-utils-hibernate-63', version: '3.7.0')
```

And then use the Type `PostgreSQLEnumType` as present in the previous versions

**Expected behavior**

No errors expected

**Comment by vladmihalcea** [comment]
The `PostgreSQLEnumType` was removed because Hibernate now provides the [`PostgreSQLEnumJdbcType`](https://docs.jboss.org/hibernate/stable/core/javadocs/org/hibernate/dialect/PostgreSQLEnumJdbcType.html) you can use instead.

**Comment by brandonfl** [comment]
Ok nice, thanks :smile:

**Comment by brandonfl** [comment]
@vladmihalcea the `PostgreSQLEnumJdbcType` is not compatible with `@Type`, did that mean that we need to remove the `@Type` completely ?

**Comment by vladmihalcea** [comment]
@brandonfl The `PostgreSQLEnumJdbcType` can be used via the `@JdbcType`. Hibernate 6 changed the Type system, so you no longer have to use the `@Type` annotation as you have other alternatives.

If you need the old `PostgreSQLEnumType`, feel free to adapt it to Hibernate 6.3 and send a Pull Request with your fix proposal.

**Comment by brandonfl** [comment]
I see, many thanks for the help :smiley:

**Comment by vladmihalcea** [comment]
You're welcome.
