### ISSUE TITLE
Use function array_to_string in SpringBoot 3.2.1

### ISSUE THREAD

**Issue by showmethemoney** [vladmihalcea/hypersistence-utils#699]
Hello 

When upgrading to SpringBoot 3.2.1, the following error occurred: `"Parameter 0 of function 'array_to_string()' requires an array type, but argument is of type 'java.lang.Collection'."`. It was working fine in SpringBoot 3.2.0.
Here are my entity property setting:
```java
 @Type(ListArrayType.class)
 @Column(name = "ip")
 List<String> ip;
```
Here are the query conditions:
```java
Expression<String> delimiter = criteriaBuilder.<String>literal(",");
Root<MyEntity> root = .....
Path attribute = root.get("ip")
criteriaBuilder.function("array_to_string", String.class, attribute, delimiter)
```

I also attempted to upgrade hypersistence-utils to hypersistence-utils-hibernate-63:3.7.1, but the issue persists. Does anyone have any suggestions?

**Comment by vladmihalcea** [comment]
@showmethemoney Try migrating to the Hibernate native array Types and see if it works.

**Comment by vladmihalcea** [comment]
@showmethemoney Give it a try with 3.7.3 as well and see if it works.

**Comment by showmethemoney** [comment]
> @showmethemoney Give it a try with 3.7.3 as well and see if it works.

ok, thanks @vladmihalcea 

Already using Hibernate native array Types and it works fine.
But I will try the solution for 3.7.3
