### ISSUE TITLE
Project failing to build as soon as implementation("com.vladmihalcea:hibernate-types-60:2.21.1") is added

### ISSUE THREAD

**Issue by BardiaRo** [vladmihalcea/hypersistence-utils#702]
hello,
I have need to parse json and I as soon as I have put the implementation("com.vladmihalcea:hibernate-types-60:2.21.1") in my dependencies:
dependencies {
  implementation("org.springframework.boot:spring-boot-starter-webflux")
  implementation("org.springframework.boot:spring-boot-starter-data-jpa")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
  implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
  implementation("org.postgresql:postgresql:42.7.2")
  implementation("com.vladmihalcea:hibernate-types-60:2.21.1")
  implementation("javax.xml.bind:jaxb-api:2.3.0")
}

 I receive the following error message: 

```java
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalArgumentException: Expecting BasicPluralJavaType for array class `[Ljava.lang.String;`, but got `com.vladmihalcea.hibernate.type.array.internal.StringArrayTypeDescriptor@574f9e36`
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
```

**Comment by vladmihalcea** [comment]
You need to migrate to version 3, as explained in the [README](https://github.com/vladmihalcea/hypersistence-utils?tab=readme-ov-file#migrating-to-version-3).

**Comment by BardiaRo** [comment]
Thanks it helped building with success, however now I am facing another issue, I have created a simpler version of my problem which I explain here:
my entity class is as follows:
```java
@Entity
@Table(name = "WM")
data class WMEntity(
  @Id
  @Column(name = "id")
  val id: Int?,

  @Type(JsonType::class)
  @Column(name = "js", columnDefinition = "jsonb")
  val wm: WM?
)
{
  constructor() : this(0,null)
}
``` 
which represents the table in database that I have and the WM data class simply looks like:
```java
data class WM(
  val js: Map<String, Int>
): Serializable

``` 
however when querying this I get:
```java
Caused by: java.lang.IllegalArgumentException: The given string value: {"str": 1} cannot be transformed to Json object
``` 
 however, if I replace the WM? type with Any?in the entity class it will work. but in my scenario cant do this because I have nested types to query. any ideas on what am I missing?

**Comment by vladmihalcea** [comment]
The project is not tested with Kotlin, so there's no guarantee it will work. If it does work, it's by  chance.

The project integration tests will show you the mappings and data access logic you can use, with Java, of course.
