### ISSUE TITLE
Equals method not found on abstract class

### ISSUE THREAD

**Issue by tomaerden-everesst** [vladmihalcea/hypersistence-utils#709]
When using hypersistence we noticed lots of jackson serialization/deserialization happens. We provide equals/hashcode implementation via an abstract class where it is implemented via reflection. Although maybe not ideal, it is a convenient solution in our project.

The code in hypersistence (https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-62/src/main/java/io/hypersistence/utils/hibernate/type/json/internal/JsonJavaTypeDescriptor.java#L108) first checks for an equals method using `getDeclaredMethod`, and the one on the parent abstract class is not found, and therefore falls back to the check using jackson read/write.

We don't get the warning as implemented on https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-62/src/main/java/io/hypersistence/utils/hibernate/type/json/internal/JsonJavaTypeDescriptor.java#L222 

Below a simple snippet illustrating our situation.

````
import io.hypersistence.utils.hibernate.util.ReflectionUtils;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

class GetDeclaredMethodTest {

    public static void main(String[] args) {
        checkForEqualsMethod(SomeType.class);
    }

    private static void checkForEqualsMethod(Class<?> targetClass) {
        var equals = ReflectionUtils.getDeclaredMethodOrNull(targetClass, "equals", new Class[]{Object.class});
        System.out.println(targetClass + " - " + equals);
    }

    private static abstract class SomeAbstractType {

        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            } else {
                return obj != null && this.getClass() == obj.getClass() ? EqualsBuilder.reflectionEquals(this, obj) : false;
            }
        }

        public int hashCode() {
            return HashCodeBuilder.reflectionHashCode(this);
        }
    }

    private static class SomeType extends SomeAbstractType{
    }

}
````

**Comment by vladmihalcea** [comment]
After a quick check, we should probably change this:

```
if (one.getClass().equals(another.getClass()) &&
	ReflectionUtils.getDeclaredMethodOrNull(one.getClass(), "equals", Object.class) != null) {
	return one.equals(another);
}
```

to this:

```
if (one.getClass().equals(another.getClass()) &&
	ReflectionUtils.getMethodOrNull(one.getClass(), "equals", Object.class) != null) {
	return one.equals(another);
}
```

Send me a Pull Request with a replicating test case and with this code change, and I'll investigate it when you are done.

**Comment by NBerghen** [comment]
@vladmihalcea I'm a colleague of Tom who created the ticket. I've made a PR with your proposal + 2 new units tests for this.

We had to change your proposal a little bit, since it would use the _java.lang.Object.equals_ method when the object had no explicit equals method implemented and thus no longer used the JsonNode equalization.

So we've excluded the Object.equals method:
```
        if (one.getClass().equals(another.getClass())) {
            Method equalsMethod = ReflectionUtils.getMethodOrNull(one.getClass(), "equals", Object.class);
            if (equalsMethod != null && !Object.class.equals(equalsMethod.getDeclaringClass())) {
                return one.equals(another);
            }
        }
```

The PR: https://github.com/vladmihalcea/hypersistence-utils/pull/712

**Comment by vladmihalcea** [comment]
Fixed.
