### ISSUE TITLE
Deprecate ZoneIdType for Hibernate 6

### ISSUE THREAD

**Issue by reitzmichnicht** [vladmihalcea/hypersistence-utils#711]
After searching if ZoneId is supported by Hibernate I had the estimation that its not supported because this great library adds special support for it.
After trying out plain Hibernate 6.4 we were surprised that in the meantime hibernate itself has added support for it, supposedly by 6.0
https://github.com/hibernate/hibernate-orm/commit/37bc00e567f7ba1ec602af28dcd9d3c06a8c0018#diff-d8c39eb8d53e8873449c3bbf841d941f2258f44edd134bae5347453ff7a6ef3d

So I guess it would be beneficial to remove duplicate support for those types for the 6.x versions of this lib.

**Comment by vladmihalcea** [comment]
Fixed

**Comment by reitzmichnicht** [comment]
Thats strange, I played around a little bit with your test. The entity itself works, but HQL query does not work. Looks like this is a bug in Hibernate maybe.
Sorry for being too optimistic about this.

**Comment by vladmihalcea** [comment]
Yes, it looks like the `ZoneId` cannot work as a `ZoneRegion` with the default Hibernate Type.
