### ISSUE TITLE
PostgreSQLCIText not implementing BindableType

### ISSUE THREAD

**Issue by flozano** [vladmihalcea/hypersistence-utils#714]
When using Hibernate 5, I used to use 

```java
 nativeQuery.setParameter(4, value, PostgreSQLCITextType.INSTANCE); 
```

this is not possible anymore in Hibernate 6, as PostgreSQLCITextType does not implement BindableType<String>. I am not sure if this is intended or a consequence of it being a ImmutableType (as all the types that inherit from MutableType are BindableType's) ... and what would be the right approach to use the PostgreSQLCITextType in this case.

**Comment by vladmihalcea** [comment]
@flozano To get that, you will have to change the `PostgreSQLCITextType` so that instead of extending `ImmutableType`, it will extend the `DescriptorImmutableType`. Looking forward to your Pull Request that fixes the issue.

**Comment by flozano** [comment]
thanks @vladmihalcea for the hint, I was trying to create a wrapper for PostgreSQLCITextType instead but your suggestion looks better.

**Comment by flozano** [comment]
Actually it was easier for me to change the code slightly to use `citext_eq` in the SQL, as this is a native query. I may attempt to contribute the PR later anyway :)

**Comment by vladmihalcea** [comment]
Closed as no PR was provided.
