### ISSUE TITLE
NullableCharacterType prevents Hibernate from escaping backslash properly

### ISSUE THREAD

**Issue by samnyan** [vladmihalcea/hypersistence-utils#715]
**Describe the bug**
When using `hypersistence-utils-hibernate-63:3.7.4` with `hibernate-core:6.4.4.Final` and `MySQL`
`like` query always failed because of the backslash hadling in `escape`

```
JDBC exception executing SQL [select p1_0.id,p1_0.label from permission p1_0 where p1_0.label like ? escape '\' limit ?,?] [Parameter index out of range (2 > number of parameters, which is 1).] [n/a]
```

The reason is in Hibernate 6 will add `escape '\'` after the like clause, and the backslash should be double backslash in sql string.
When not using hypersistence-utils, the output sql is correct: 
```
Hibernate: select p1_0.id,p1_0.label from permission p1_0 where p1_0.label like ? escape '\\' limit ?,?
```

But adding hypersistence-utils will cause the above error.

Because in `org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.renderLiteral()`, by default it will use `org.hibernate.type.descriptor.jdbc.internal.JdbcLiteralFormatterCharacterData` to append the sql which using [org.hibernate.dialect.MySQLDialect.appendLiteral()](https://github.com/hibernate/hibernate-orm/blob/fe7b3c9e7eab1cc328429ae9356ed5a0eb27bcfd/hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java#L1299) method. This can handle backslash in sql correctly.

But when adding hypersistence-utils,
The JdbcMapping type became `io.hypersistence.utils.hibernate.type.basic.NullableCharacterType`,
and it will use [org.hibernate.type.internal.UserTypeSqlTypeAdapter](https://github.com/hibernate/hibernate-orm/blob/fe7b3c9e7eab1cc328429ae9356ed5a0eb27bcfd/hibernate-core/src/main/java/org/hibernate/type/internal/UserTypeSqlTypeAdapter.java#L95) to append the sql instead.
Then it calls [io.hypersistence.utils.hibernate.type.ImmutableType.toSqlLiteral()](https://github.com/vladmihalcea/hypersistence-utils/blob/de9a7f5ccaef0b5c325f0cbdc2f36735b2150231/hypersistence-utils-hibernate-63/src/main/java/io/hypersistence/utils/hibernate/type/ImmutableType.java#L295) which using `String.format(Locale.ROOT, "'%s'", o)` inside.
The result is only one backslash in the sql string. (Breaking the following sql statement prepare)

**Comment by vladmihalcea** [comment]
You can remove the NullCharacterType from auto-registration. Just provide your own TypesContributors without that Type.

I think this NullableCharacterType could be removed from the default TypeContributors as it should be opted explicitly.

**Comment by vladmihalcea** [comment]
Fixed.
