### ISSUE TITLE
ListArrayType on Set entity attribute fails for EntityManager.merge operation

### ISSUE THREAD

**Issue by aleksei-konahav** [vladmihalcea/hypersistence-utils#717]
**Describe the bug**
`ListArrayType` on `Set` entity attribute ([like in this test](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-63/src/test/java/io/hypersistence/utils/hibernate/type/array/ListArrayTypeTest.java#L536)) leads to the `Can not set java.util.Set field ... to java.util.ArrayList` error.

**To Reproduce**

Using existing test cases, just change `persist` to `merge` in existing test ([line reference](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-63/src/test/java/io/hypersistence/utils/hibernate/type/array/ListArrayTypeTest.java#L76)):
```java
entityManager.merge(
    new Event()
        .setId(1L)
        .setSensorIds(
```

**Expected behavior**
As for now, you will get an exception, while expecting `merge` operation to be successfully completed.

**Additional context**
This seems to be an issue in `ListArrayTypeDescriptor`, and its [`MutableMutabilityPlan.deepCopyNotNull`](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-63/src/main/java/io/hypersistence/utils/hibernate/type/array/internal/ListArrayTypeDescriptor.java#L36) implementation in particular. It always returns `ArrayList`, while actual attribute type maybe be `List` or `Set`.

Seems like it should consider actual `propertyClass`, like we have in [`newPropertyCollectionInstance`](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-63/src/main/java/io/hypersistence/utils/hibernate/type/array/internal/ListArrayTypeDescriptor.java#L134) method in the same class.

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request that fixes the problem.

**Comment by josevsgeon** [comment]
what's the status of this? is the PR ready for merge? I'm facing the same issue.

**Comment by vladmihalcea** [comment]
1. The status id Open. 
2. I don't know since I didn't have time to review it.

**Comment by vladmihalcea** [comment]
Fixed.
