### ISSUE TITLE
Is Hibernate 6.5 supported?

### ISSUE THREAD

**Issue by N4SoftwareNinja** [vladmihalcea/hypersistence-utils#722]
Hi,

since in the readme 6.5 is not mentioned, does that mean it is not supported yet?
Or is the readme simply outdated and using hypersistence-utils-hibernate-63 with Hibernate 6.5 is totally fine?

PS: Thanks for this amazing library :)

**Comment by vladmihalcea** [comment]
The library was never tested with Hibernate 6.5, so it could either work or not. 

You have to try it with Hibernate 6.5 and see if it works.
