### ISSUE TITLE
Enhance BatchSequenceGenerator with support for IdGeneratorType

### ISSUE THREAD

**Issue by marschall** [vladmihalcea/hypersistence-utils#728]
Hibernate 6.5 has deprecated `@GenericGenerator` see https://discourse.hibernate.org/t/deprecation-of-genericgenerator-in-hibernate-6-5/9482. Instead the `@IdGeneratorType` meta-annotation should be used https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators-IdGeneratorType

The result is a lot less verbose, what previously was

```java
  @Id
  @GenericGenerator(
          name = "parent_id_generator",
          strategy = "com.github.marschall.hibernate.batchsequencegenerator.BatchSequenceGenerator",
          parameters = {
              @Parameter(name = SEQUENCE_PARAM, value = "SEQ_PARENT_ID"),
              @Parameter(name = FETCH_SIZE_PARAM, value = "50")
          })
  @GeneratedValue(generator = "parent_id_generator")
  private Long parentId;
```

Is now simply

```java
  @Id
  @BatchSequence(name = "SEQ_PARENT_ID", fetchSize = 50)
  private Long parentId;
```
Here is an example what the changes may look like  https://github.com/marschall/hibernate-batch-sequence-generator/commit/d88975a0be56703e4431d2bb829b47be6b409692

I'm not sure this can be retrofitted into the 6.3 module or a new 6.5 module is needed.

**Comment by vladmihalcea** [comment]
Fixed.
