### ISSUE TITLE
Add support for mapping Java Enums to custom ordinal values

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-utils#730]
To achieve this goal, the new `CustomOrdinalEnumConverter` will be used as the base class of the actual Enum Converter type that will provide the custom ordinal value:

```
@Converter
public class PostStatusConverter 
	extends CustomOrdinalEnumConverter<PostStatus> {

	public PostStatusConverter() {
		super(PostStatus.class);
	}

	@Override
	public Integer convertToDatabaseColumn(PostStatus enumValue) {
		return enumValue.getStatusCode();
	}
}
```

For more details, check out [this article](https://vladmihalcea.com/java-enum-custom-values/).

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by glandais-mdm** [comment]
It would be great to include enhancements in a GitHub release, I had to search a little bit to understand what's new in our Renovate MR for upgrading to 3.8.0

**Comment by vladmihalcea** [comment]
The [3.8 release includes this enhancement](https://github.com/vladmihalcea/hypersistence-utils/milestone/80?closed=1). I'm not sure what you mean by "GitHub release", but since the dependency is on Maven Central and the GitHub Milestone tells you what's changed, then it's all good.

**Comment by glandais-mdm** [comment]
Ok I'm just dumb and was looking for something like that : https://github.com/spring-projects/spring-boot/releases
It may be easy to create a release from an achieved milestone, but it's really only a small bonus. Renovate is able to look for Milestones anyway, I was just too in a hurry to discover what was new in 3.8.0 directly from GitHub
Thanks for your awesome work, you're my ref when I'm looking something about JPA !

![image](https://github.com/vladmihalcea/hypersistence-utils/assets/156188371/a34e9336-e0c1-45f2-b2b2-7b5d02ad1d54)
