### ISSUE TITLE
\u0000 cannot be converted to text

### ISSUE THREAD

**Issue by suikast42** [vladmihalcea/hypersistence-utils#738]
If some jsonb columns contains  \u0000  characters then the pertitence fails on postgres. 

Is there a common way to replace those invalid json chracters before persist ?

**Comment by vladmihalcea** [comment]
There's always a way. Looking forward to your Pull Request that demonstrates the issue and provides the fix for it

**Comment by vladmihalcea** [comment]
Closed as no Pull Request was provided.
