### ISSUE TITLE
Support for GraalVM Native Image

### ISSUE THREAD

**Issue by alapierre** [vladmihalcea/hypersistence-utils#740]
I'm useing Micronaut framework with Micronaut Data and I'm trying to facilitate GraalVM Native Image. Every think works fine how long I'm not using `PostgreSQLRangeType`. Problem is in lack of reflection metadata for GraalVM.

**To Reproduce**

sample project: https://github.com/micronaut-projects/micronaut-data

**Comment by vladmihalcea** [comment]
@alapierre Try to replace the Reflection calls with [Method Handles](https://dev.java/learn/introduction_to_method_handles/), build the project, and see if it works.

**Comment by rajat-g** [comment]
@alapierre You can use this below json(reflect-config.json) to use `PostgreSQLRangeType`
place the configuration file under the src/main/resources/META-INF/native-image/<group-id>/<artifact-id> folder.


`
[
  {
    "name": "org.postgresql.util.PGobject",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      },
      {
        "name": "setType",
        "parameterTypes": [
          "java.lang.String"
        ]
      },
      {
        "name": "setValue",
        "parameterTypes": [
          "java.lang.String"
        ]
      }
    ]
  }
]
`
