### ISSUE TITLE
Allow PostgreSQLCITextType entity attributes to be used in the LIKE query clause

### ISSUE THREAD

**Issue by SimSonic** [vladmihalcea/hypersistence-utils#743]
Spring Boot 3.3.3 (hibernate 6.5.2). PostgreSQL 14.2, hypersistence-utils 3.8.2.

```sql
SELECT e
FROM SomeEntity AS e
WHERE s.textField LIKE :search
```

```java
@Entity
@Table(name = "table_name")
// ...
SomeEntity {
   
   @Type(PostgreSQLCITextType.class)
   @Column(name = "text_field", columnDefinition = "CITEXT")
   private String textField;

   // ...
}
```

![image](https://github.com/user-attachments/assets/84f1ba86-650a-4f49-93c9-47d5ac7b1539)

The exception is thrown from here:

![image](https://github.com/user-attachments/assets/9a452851-57e8-4263-a9dc-132caf46e2f3)

the cause is that PostgreSQLCITextType returns SlqTypes.OTHER which type returns .isStringLike() = false.

The same code was working before migration from Spring 2.7.18.

What can we do to use LIKE with CITEXT columns?

Thanks.

**Comment by vladmihalcea** [comment]
`PostgreSQLCITextType` should use something like `Types.VARCHAR` instead of `Types.OBJECT`.

**Comment by vladmihalcea** [comment]
Fixed.
