### ISSUE TITLE
dto projectin error when use jsonb field

### ISSUE THREAD

**Issue by a-morgan-developer** [vladmihalcea/hypersistence-utils#747]
this is my entity:
`@Entity
public class Request {

    public Request() {
    }

    public Request(AddRequestCommand command) {
        this.type = command.getRequestType();
        this.params = command.getParams();
        this.status = RequestPendingType.PENDING;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "request_sequence")
    @SequenceGenerator(name = "request_sequence", sequenceName = "request_seq", allocationSize = 10)
    private Integer id;

    @Enumerated(EnumType.STRING)
    RequestType type;

    @Enumerated(EnumType.STRING)
    RequestPendingType status;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "device_id", nullable = false)
    Device device;

    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    String params;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;`
}
i use springboot  and spring data jpa
in service layer, when i query the Request and return type is Request all thing is good. but when i want dto projection i get this error :
`org.hibernate.query.sqm.sql.internal.InstantiationException: Cannot set field 'params' to instantiate 'com.example.server.dto.RequestDto'
` 
this is my dto:
`public class RequestDto {

    private Integer id;
    private RequestType type;
    private RequestPendingType status;
    private String params;

    public RequestDto(Integer id, RequestType type, RequestPendingType status, String params) {
        this.id = id;
        this.type = type;
        this.status = status;
        this.params = params;
    }
    }`
    * getter an setter removed
    i use spring boot 3.3.3 version and hypersistence-utils-hibernate-63 version 3.8.3 version

**Comment by vladmihalcea** [comment]
The problem comes from the framework you are using to create the DTO projection. You will have to configure that to perform the same mapping logic as the `JsonType` does for entities.
