### ISSUE TITLE
How to Implement the Assigned Identity Generator？

### ISSUE THREAD

**Issue by hell0w0orld** [vladmihalcea/hypersistence-utils#757]
The version I am using is Hypersistence-Utils-hibernate-63: 3.8.3

I want to implement the Assigned Identity Generator. I have browsed through your previous blog about its implementation, but the current version is no longer applicable. I am trying to implement the function, but I am not sure if it is correct. I hope to receive your reply. Thank you very much.

Here is the code for the previous blog implementation, blog address: https://vladmihalcea.com/how-to-combine-the-hibernate-assigned-generator-with-a-sequence-or-an-identity-column/
```
public class AssignedIdentityGenerator
    extends IdentityGenerator {
 
    @Override
    public Serializable generate(SessionImplementor session,
        Object obj) {
        if(obj instanceof Identifiable) {
            Identifiable identifiable = (Identifiable) obj;
            Serializable id = identifiable.getId();
            if(id != null) {
                return id;
            }
        }
        return super.generate(session, obj);
    }
}
```
Here is a partial code I have implemented:
```
public class AssignedIdentityGenerator extends Assigned {

    @Override
    public Object generate(SharedSessionContractImplementor s, Object obj) {
        if (obj instanceof SysBase t && t.getId() == null) {
            return IdentifierGeneratorHelper.getGeneratedIdentity(xxx);
        }

        return super.generate(s, obj);
    }
}
```

**Comment by vladmihalcea** [comment]
@hell0w0orld You can ask the question on the [Hibernate forum](https://discourse.hibernate.org/). The Hibernate developers can better help you with this since they are more familiar with the changes that were done lately on the entity identifiers.
